/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import { useCallback } from 'react';
import { useAppStore } from '../../stores/appStore';

export function useSettingsActions() {
  const { setCurrentChildPage } = useAppStore();

  const goToProfile = useCallback(() => {
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {
      setCurrentChildPage('profile');
    }, 100);
  }, [setCurrentChildPage]);

  const goToPreferences = useCallback(() => {
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {
      setCurrentChildPage('preferences');
    }, 100);
  }, [setCurrentChildPage]);

  return {
    goToProfile,
    goToPreferences
  };
}