<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './appStore';
export * from './authStore';
export * from './chessGameStore';
export * from './puzzleStore';
export * from './workerTestStore';
=======
// Auto-generated barrel export for stores
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './appStore';
export * from './chessGameStore';
export * from './puzzleStore';
export * from './workerTestStore';

// Mixed exports (default + named)
export * from './authStore';
export { default as authStore } from './authStore';

// Default export for single component barrel
export { default as default } from './authStore';
>>>>>>> Stashed changes
