/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import React, { useEffect } from 'react';
import { LoginPage } from '../../pages/user/LoginPage';
import { useAppStore } from '../../stores/appStore';

export type AuthPage = 'login' | 'register' | 'forgotPassword';

interface AuthRouterProps {
  initialPage?: AuthPage;
}

const AuthRouter: React.FC<AuthRouterProps> = () => {
  const setCurrentChildPage = useAppStore((state: any) => state.setCurrentChildPage);

  // Initialize to login state on mount
  useEffect(() => {
    setCurrentChildPage(null); // Always start with login (main page)
  }, [setCurrentChildPage]);

  // Only render LoginPage - it handles all child navigation internally
  return <LoginPage />;
};

export default AuthRouter;