<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './AuthBackgroundEffects';
export * from './AuthComponent';
export * from './AuthLayout';
export * from './AuthRouter';
export * from './DemoLoginButton';
=======
// Auto-generated barrel export for auth
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './ForgotPasswordPageWrapper';
export * from './RegisterPageWrapper';

// Default exports
export { default as AuthBackgroundEffects } from './AuthBackgroundEffects';
export { default as AuthLayout } from './AuthLayout';

// Mixed exports (default + named)
export * from './AuthRouter';
export { default as AuthRouter } from './AuthRouter';
export * from './DemoLoginButton';
export { default as DemoLoginButton } from './DemoLoginButton';
>>>>>>> Stashed changes
