/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 *
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 *
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 *
 * Then re-run the generator to update this file.
 */
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: {
            '@': resolve(__dirname, './src'),
        },
    },
});
