<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

=======
// Auto-generated barrel export for chess
// Generated by AdvancedBarrelGenerator

// Named exports only
>>>>>>> Stashed changes
export * from './ChessGameService';
export * from './ComputerOpponentService';
export * from './FenService';
export * from './MobileChessGameService';
export * from './PlayGameService';
<<<<<<< Updated upstream
export * from './stockfish-singleton';
export * from './StockfishService';
export * from './TestBoardGameService';
=======
export * from './StockfishService';
export * from './TestBoardGameService';
export * from './stockfish-singleton';
>>>>>>> Stashed changes
