/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// Shared WrapperPiece interface for chess board animations

export interface WrapperPiece {
  id: string;
  color: string;
  type: string;
  x: number; // Pixel position
  y: number; // Pixel position
  opacity: number;
  isAnimating: boolean;
  boardPosition: string; // Chess notation (e.g., 'a1', 'e4')
  scale: number; // Scale for capture animation
}