/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
// Mobile hook import will be added when mobile support is enabled
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useDiscoverActions } from "../../hooks/discover/useDiscoverActions";
import { DiscoverMainPage } from "./DiscoverMainPage";

import { GenresPageWrapper } from "../../components/discover/GenresPageWrapper";
import { TrendingPageWrapper } from "../../components/discover/TrendingPageWrapper";

interface DiscoverPageProps {
  // Add props as needed
}

export const DiscoverPage: React.FC<DiscoverPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  // Mobile detection will be added when mobile support is enabled
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("discover");
  usePageActions("discover");
  
  // Use parent actions hook for navigation methods
  useDiscoverActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = DiscoverMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "genres") {
    CurrentPageComponent = GenresPageWrapper;
  } else  if (currentChildPage === "trending") {
    CurrentPageComponent = TrendingPageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="discover"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};