// Auto-generated barrel export for core
// Generated by AdvancedBarrelGenerator

// Named exports only
export * as BackgroundEffectsService from './BackgroundEffectsService';
export * as backgroundEffectsRegistry from './backgroundEffectsRegistry';
