/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export * from './auth.service';

export { puzzleApiService } from './api';
export { getStockfishSingletonStats, ComputerOpponentService, TestBoardGameService, PlayGameService, MobileChessGameService, ChessGameService, FenService, getStockfishService, destroyStockfishSingleton, StockfishService } from './chess';
export type { MoveResult, PieceColor, GameStatus, GameState, StockfishHandlers } from './chess';
export { StockfishEngineClient } from './clients';
export { instructionsService, InstructionsService } from './instructions';
export type { PageInstructions } from './instructions';
export { AssetCacheService, preloadingService, assetCacheService, PreloadingService } from './preloading';
export type { LoadingProgress, LoadingPriority, LoadingResults } from './preloading';