/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { validate } from '../middleware/validation';
import { PuzzleService } from '../services/puzzlesService';
import { PuzzleResponse, CreatePuzzleRequest, UpdatePuzzleRequest } from '../models/Puzzle';

const router = Router();
const puzzlesService = new PuzzleService();

// GET /next
router.get('/next', authenticate, async (req: any, res) => {
  try {
    const result = await puzzlesService.getNextPuzzle();
    res.json({ success: true, data: result });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// POST /:id/solve
router.post('/:id/solve', authenticate, async (req: any, res) => {
  try {
    const result = await puzzlesService.solvePuzzle(req.params.id);
    res.json({ success: true, data: result });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// GET /:id/hint
router.get('/:id/hint', authenticate, async (req: any, res) => {
  try {
    const result = await puzzlesService.getPuzzleHint(req.params.id);
    res.json({ success: true, data: result });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

export default router;