<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './AnimatedSplashPageWrapper';
export * from './BrandedSplashPageWrapper';
export * from './FunctionalSplashPageWrapper';
export * from './LoadingProgressPageWrapper';
export * from './LuxurysplashPageWrapper';
export * from './MinimalSplashPageWrapper';
export * from './SplashModal';
export { default as withSplashScreen } from './withSplashScreen';
=======
// Auto-generated barrel export for splash
// Generated by AdvancedBarrelGenerator

// Default exports
export { default as AnimatedSplashPageWrapper } from './AnimatedSplashPageWrapper';
export { default as BrandedSplashPageWrapper } from './BrandedSplashPageWrapper';
export { default as FunctionalSplashPageWrapper } from './FunctionalSplashPageWrapper';
export { default as LoadingProgressPageWrapper } from './LoadingProgressPageWrapper';
export { default as MinimalSplashPageWrapper } from './MinimalSplashPageWrapper';
export { default as withSplashScreen } from './withSplashScreen';

// Mixed exports (default + named)
export * from './LuxurysplashPageWrapper';
export * from './SplashModal';
>>>>>>> Stashed changes
