/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

/**
 * Dynamic ActionSheetContainer - Generated from pages.config.json
 * 
 * This container automatically imports and maps all generated page action hooks
 * and uses the PAGE_ACTIONS registry for dynamic action discovery.
 */
import { useCallback } from "react";
import ActionSheet from "./ActionSheet";
import { useUIClickSoundOptimized } from "../../hooks/audio/useUIClickSoundOptimized";
import { useUIHoverSoundOptimized } from "../../hooks/audio/useUIHoverSoundOptimized";
import { useActionSheetDelayedPage } from "../../hooks/useActionSheetDelayedPage";
import { useNavigation } from "../../stores/uiStore";
import { useAuthStore } from "../../stores/authStore";
import type {
  ActionSheetContainerProps,
  ActionSheetAction,
} from "../../types/core/action-sheet.types";
import { PAGE_ACTIONS } from "../../constants/actions/page-actions.constants";

// Dynamic imports for generated page action hooks
import { useTestingActions } from "../../hooks/testing/useTestingActions";
import { useDataAnalyticsActions } from "../../hooks/dataanalytics/useDataAnalyticsActions";
import { useGameHubActions } from "../../hooks/gamehub/useGameHubActions";
import { useUserManagementActions } from "../../hooks/usermanagement/useUserManagementActions";
import { useTestBackupActions } from "../../hooks/testbackup/useTestBackupActions";
import { useTestSectionActions } from "../../hooks/testsection/useTestSectionActions";

export default function ActionSheetContainer({
  currentPage,
  className,
  onClose,
  isOpen,
  onOpenSettings,
}: ActionSheetContainerProps) {
  // Use child page if it exists, otherwise use current tab
  const { currentChildPage } = useNavigation();
  const actionSheetPage = currentChildPage || currentPage;

  // Add delay when switching action menus (only for child page changes, not main tab changes)
  const delayedActionSheetPage = useActionSheetDelayedPage(
    actionSheetPage,
    currentPage,
    currentChildPage
  );

  // Get actions for current page (with delay)
  const actions = PAGE_ACTIONS[delayedActionSheetPage] || [];

  // Initialize all generated action hooks (dynamic)
  const testingActions = useTestingActions();
  const dataanalyticsActions = useDataAnalyticsActions();
  const gamehubActions = useGameHubActions();
  const usermanagementActions = useUserManagementActions();
  const testbackupActions = useTestBackupActions();
  const testsectionActions = useTestSectionActions();

  // Audio for action clicks and hovers
  const { playUIClick } = useUIClickSoundOptimized();
  const { playUIHover } = useUIHoverSoundOptimized();

  // Auth store for logout
  const logout = useAuthStore((state: any) => state.logout);

  // Action handler - handles global actions and dynamic page actions
  const handleAction = useCallback(
    (action: ActionSheetAction, closeCallback: () => void) => {
      playUIClick();

      // Handle global settings action
      if (action.id === "open-settings") {
        onOpenSettings();
        closeCallback();
        return;
      }

      // Handle logout action
      if (action.id === "logout") {
        console.log("🚪 [ACTION SHEET] Logging out user...");
        logout();
        closeCallback();
        return;
      }

      // Handle dynamic page actions using generated hooks
      const actionMap: Record<string, Record<string, () => void>> = {
      pageone: {
        "go-to-pagetwo": testsectionActions.goToPageTwo,
      },
      pagetwo: {
        "go-to-pageone": testsectionActions.goToPageOne,
      },
      testsection: {
        "go-to-pageone": testsectionActions.goToPageOne,
        "go-to-pagetwo": testsectionActions.goToPageTwo,
      },
      };

      const pageActions = actionMap[delayedActionSheetPage];
      const actionFunction = pageActions?.[action.id];

      if (actionFunction) {
        try {
          actionFunction();
          closeCallback();
        } catch (error) {
          console.error(`❌ [ACTION SHEET] Action ${action.id} failed:`, error);
        }
      } else {
        console.warn(
          `⚠️ [ACTION SHEET] No handler for action '${action.id}' on page '${delayedActionSheetPage}'`
        );
        closeCallback();
      }
    },
    [
      delayedActionSheetPage,
      onOpenSettings,
      logout,
      playUIClick,
      // Dynamic hook dependencies
    testingActions,
    dataanalyticsActions,
    gamehubActions,
    usermanagementActions,
    testbackupActions,
    testsectionActions,
    ]
  );

  const handleHover = useCallback(() => {
    playUIHover();
  }, [playUIHover]);

  const handleKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose?.();
      }
    },
    [onClose]
  );

  // Filter actions based on authentication state if needed  
  const filteredActions = actions.filter(() => {
    // Add any authentication-based filtering here if needed
    return true;
  });

  return (
    <ActionSheet
      actions={filteredActions}
      onActionClick={handleAction}
      onActionHover={handleHover}
      onKeyDown={handleKeyDown}
      onClose={onClose}
      isOpen={isOpen}
      className={className}
    />
  );
}

// Named export for flexibility
export { ActionSheetContainer };