/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ChildPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/child_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { ProfilePage } from "../../pages/settings/ProfilePage";
import { MobileProfilePage } from "../../pages/settings/MobileProfilePage";

export const ProfilePageWrapper: React.FC = () => {
  // Mobile detection handled in wrapper (Phase 2 Architecture)
  const isMobile = useIsMobile();
  
  // Apply page context
  usePageInstructions("profile");
  usePageActions("profile");

  // Internal mobile/desktop switching
  return isMobile ? <MobileProfilePage /> : <ProfilePage />;
};