/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import { useAuthStore } from "../stores/authStore";

export function useAuthStatus() {
  const { isAuthenticated, isLoading } = useAuthStore();
  
  return {
    isAuthenticated,
    isLoading
  };
}