<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './InstructionsService.dynamic';
export * from './InstructionsService';
=======
// Auto-generated barrel export for instructions
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './InstructionsService';

// Subdirectory exports
export * from './pages';
>>>>>>> Stashed changes
