<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './StockfishEngineClient';
=======
// Auto-generated barrel export for clients
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './StockfishEngineClient';
>>>>>>> Stashed changes
