/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'animatedsplash',
  title: `Progressive Piece Assembly`,
  instructions: [
    `♗ Chess pieces appear in logical hierarchy sequence`,
    `🎭 Staggered timing creates engaging assembly animation`,
    `📚 Educational value showing piece placement learning`,
    `🔄 Restart animation to see full piece assembly sequence`,
    `🎮 Test cross-navigation to other splash variants`,
  ]
}