/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'blackjack',
  title: `Chess Blackjack Coming Soon`,
  instructions: [
    `Chess-themed blackjack game with traditional rules`,
    `Play against the dealer with chess piece card designs`,
    `Try to get as close to 21 without going over`,
    `Use the action menu to navigate to other casino games`,
  ]
}