/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'casino',
  title: `Chess Casino Games Hub`,
  instructions: [
    `Welcome to the chess-themed casino! Choose from our exciting selection of games`,
    `Navigate between different casino games using the action menu`,
    `All games feature chess piece symbols and themes for a unique experience`,
    `Start with slots for the full casino slot machine experience`,
  ]
}