/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'craps',
  title: `Chess Craps Dice Game`,
  instructions: [
    `Chess-themed craps with simplified mobile-friendly rules`,
    `Roll the dice with chess piece patterns`,
    `Place bets on various dice outcomes and combinations`,
    `Enjoy the fast-paced excitement of this classic casino game`,
  ]
}