/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'desktoplayouttest',
  title: `Desktop Layout Testing`,
  instructions: [
    `Test the AuthLayout pinning pattern applied to desktop chess layouts`,
    `Use "Toggle Layout Elements" to show/hide surrounding layout components`,
    `Observe how the layout pins between top controls and bottom tabbar`,
    `Test the three-layer flex structure: flex-1 → items-stretch → justify-center`,
    `Verify proper spacing and responsive behavior on desktop screens`,
  ]
}