/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'loadingprogress',
  title: `Engine Loading Dashboard`,
  instructions: [
    `🔧 Technical precision meets chess sophistication`,
    `📊 Real progress feedback for engine initialization sequence`,
    `🎯 Professional dashboard styling with readable timing`,
    `⚙️ Shows current service being initialized`,
    `🔄 Restart to see full loading sequence animation`,
  ]
}