/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'minimalsplash',
  title: `Minimal Professional Splash`,
  instructions: [
    `🎨 Clean single logo + brand colors with professional typography`,
    `👑 Floating chess crown symbol with subtle animation`,
    `⏱️ 1.5-2 second duration for quick professional impression`,
    `🔄 Restart animation using action sheet controls`,
    `🚀 Navigate to other splash screen examples`,
  ]
}