/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'mobiledragtest',
  title: `Mobile Chess Board Testing`,
  instructions: [
    `Test the wrapper-based chess board animation system`,
    `Use action sheet to reset the board to initial position`,
    `Test move sounds and capture animations`,
    `Experience smooth piece animations and shrinking capture effects`,
  ]
}