/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'playpuzzles',
  title: `Chess Puzzle Training`,
  instructions: [
    `Sharpen your tactical skills with our comprehensive puzzle collection`,
    `Solve mate-in-1, mate-in-2, tactical combinations, and endgame studies`,
    `Learn from famous positions in chess history`,
    `Get hints when you're stuck or reveal the full solution`,
    `Use action menu for puzzle controls: New Puzzle, Hint, Solve Puzzle`,
  ]
}