/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'play',
  title: `Chess Play Hub`,
  instructions: [
    `Welcome to the Chess Play Hub - Your gateway to chess gameplay`,
    `Choose between classical chess games or challenging puzzles`,
    `Navigate using the action menu to select your preferred play mode`,
    `Each mode offers unique features and learning opportunities`,
  ]
}