/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'slots',
  title: `Chess Slot Machine Experience`,
  instructions: [
    `Experience the thrill of a chess-themed casino slot machine`,
    `Use the +/- buttons to adjust your coin wager amount`,
    `Click the SPIN button to start the slot machine animation`,
    `Watch for winning chess piece combinations and enjoy the casino atmosphere`,
  ]
}