/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'uiaudiotest',
  title: 'UIAudioTest Instructions',
  instructions: [
    'UI audio testing page',
    'Use the action sheet to interact with available options',
    'This page automatically adapts between mobile and desktop layouts'
  ]
}