/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'uitests.drag-test',
  title: `Interactive Chess Board Guide`,
  instructions: [
    `Test drag and drop functionality with visual feedback and capture mechanics`,
    `Drag the bottom-right corner of the dashed container to test responsive scaling`,
    `Click on squares to select them and see valid drop targets highlighted`,
    `Experience professional chess drag interactions`,
  ]
}