/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'uitests.mobile-drag-test',
  title: `Mobile Chess Board Guide`,
  instructions: [
    `Test mobile-optimized chess board interactions`,
    `Experience touch-friendly drag and drop functionality`,
    `See how the board adapts to mobile screen constraints`,
    `Test mobile-specific chess interaction patterns`,
  ]
}