/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export const pageInstructions = {
  id: 'worker',
  title: `Chess Computer Testing Guide`,
  instructions: [
    `Test if the chess computer is working and ready to play games`,
    `Check how fast the computer can think and respond to moves`,
    `Adjust the computer's skill level from beginner to expert`,
    `Run quick tests to verify the chess engine is functioning properly`,
  ]
}