/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// componentDetection.ts - React component identification utilities

/**
 * Safely get className as string
 */
function getClassName(element: HTMLElement): string {
  const className = element.className;
  return typeof className === 'string' ? className : '';
}

/**
 * Identify React components by walking up the DOM tree
 */
export function identifyReactComponent(element: HTMLElement): string[] {
  const components: string[] = [];
  let current: HTMLElement | null = element;
  
  // Look for component identifiers in class names, data attributes, and structure
  while (current && current !== document.body) {
    // Check for component-like class names
    const className = getClassName(current);
    const classNames = className.split(' ').filter(c => c.length > 0);
    
    for (const cls of classNames) {
      // Look for specific component patterns first, then general ones
      if (cls.includes('tab-button')) {
        if (cls.includes('active')) {
          components.push('TabButton-Active');
        } else {
          components.push('TabButton');
        }
      } else if (cls.includes('menu-button')) {
        components.push('MenuButton');
      } else if (cls.includes('fab') || cls.includes('FAB') || cls.includes('floating')) {
        components.push('FloatingActionButton');
      } else if (cls.includes('settings') || cls.includes('Settings')) {
        components.push('SettingsButton');
      } else if (cls.includes('theme') || cls.includes('Theme')) {
        components.push('ThemeButton');
      } else if (cls.includes('dropdown') || cls.includes('Dropdown')) {
        components.push('DropdownButton');
      } else if (cls.includes('icon') || cls.includes('Icon')) {
        components.push('IconButton');
      } else if (cls.includes('menu') || cls.includes('Menu')) {
        components.push('Menu');
      } else if (cls.includes('tab') || cls.includes('Tab')) {
        components.push('Tab');
      } else if (cls.includes('button') || cls.includes('Button') || cls.includes('btn')) {
        components.push('Button');
      } else if (cls.includes('header') || cls.includes('Header')) {
        components.push('Header');
      }
    }
    
    // Check for data attributes that might indicate component
    const dataComponent = current.getAttribute('data-component');
    if (dataComponent) {
      components.push(`[data-component="${dataComponent}"]`);
    }
    
    // Check for common React component patterns in IDs
    const id = current.id;
    if (id) {
      if (id.includes('menu')) components.push('Menu-related');
      if (id.includes('tab')) components.push('Tab-related');
      if (id.includes('header')) components.push('Header-related');
      if (id.includes('button')) components.push('Button-related');
    }
    
    // Check for button elements specifically
    if (current.tagName === 'BUTTON') {
      components.push('Button-element');
    }
    
    // Check for interactive elements
    if (current.hasAttribute('onClick') || current.hasAttribute('onclick')) {
      components.push('Clickable');
    }
    
    current = current.parentElement;
  }
  
  return [...new Set(components)]; // Remove duplicates
}

/**
 * Get DOM element path for debugging
 */
export function getElementPath(element: HTMLElement): string {
  const path: string[] = [];
  let current: HTMLElement | null = element;
  let depth = 0;
  
  while (current && current !== document.body && depth < 5) {
    let selector = current.tagName.toLowerCase();
    
    if (current.id) {
      selector += `#${current.id}`;
    } else if (current.className && typeof current.className === 'string') {
      const classes = current.className.split(' ').filter(c => c.length > 0).slice(0, 2);
      if (classes.length > 0) {
        selector += `.${classes.join('.')}`;
      }
    }
    
    path.unshift(selector);
    current = current.parentElement;
    depth++;
  }
  
  return path.join(' > ');
}

/**
 * Get safe element information for logging
 */
export function getElementInfo(element: HTMLElement) {
  return {
    tagName: element.tagName,
    className: getClassName(element),
    id: element.id || '',
    textContent: element.textContent?.slice(0, 50) || '',
    dataset: element.dataset || {},
    reactComponent: identifyReactComponent(element),
    elementPath: getElementPath(element)
  };
}