/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// deviceDetection.ts - Device detection utilities for audio service

export interface DeviceInfo {
  isMobile: boolean;
  deviceType: '📱 MOBILE' | '🖥️ DESKTOP';
}

/**
 * Detect if the current device is mobile
 */
export function detectMobile(): boolean {
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ||
         ('ontouchstart' in window) ||
         (navigator.maxTouchPoints > 0);
}

/**
 * Get device information with formatted labels
 */
export function getDeviceInfo(): DeviceInfo {
  const isMobile = detectMobile();
  return {
    isMobile,
    deviceType: isMobile ? '📱 MOBILE' : '🖥️ DESKTOP'
  };
}