/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
// Mobile hook import will be added when mobile support is enabled
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useProfileActions } from "../../hooks/profile/useProfileActions";
import { ProfileMainPage } from "./ProfileMainPage";

import { SettingsPageWrapper } from "../../components/profile/SettingsPageWrapper";
import { StatsPageWrapper } from "../../components/profile/StatsPageWrapper";

interface ProfilePageProps {
  // Add props as needed
}

export const ProfilePage: React.FC<ProfilePageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  // Mobile detection will be added when mobile support is enabled
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("profile");
  usePageActions("profile");
  
  // Use parent actions hook for navigation methods
  useProfileActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = ProfileMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "settings") {
    CurrentPageComponent = SettingsPageWrapper;
  } else  if (currentChildPage === "stats") {
    CurrentPageComponent = StatsPageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="profile"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};