/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useDataAnalyticsActions } from "../../hooks/dataanalytics/useDataAnalyticsActions";
import { DataAnalyticsMainPage } from "./DataAnalyticsMainPage";

import { MobileDataAnalyticsMainPage } from "./MobileDataAnalyticsMainPage";
// Child imports will be added here when children are created

interface DataAnalyticsPageProps {
  // Add props as needed
}

export const DataAnalyticsPage: React.FC<DataAnalyticsPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  const isMobile = useIsMobile();
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("dataanalytics");
  usePageActions("dataanalytics");
  
  // Use parent actions hook for navigation methods
  useDataAnalyticsActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = isMobile ? MobileDataAnalyticsMainPage : DataAnalyticsMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
  // Child routing logic will be added here when children are created
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="dataanalytics"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};