<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './AppLayout';
export * from './BackgroundEffects';
export * from './Header';
export * from './MainContent';
export * from './MenuButton';
export * from './MenuDropdown';
export * from './TabBar';
export * from './TitleBar';
export * from './types';
=======
// Auto-generated barrel export for layout
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './BackgroundEffects';
export type * from './types';

// Default exports
export { default as AppLayout } from './AppLayout';
export { default as Header } from './Header';
export { default as MenuButton } from './MenuButton';
export { default as MenuDropdown } from './MenuDropdown';
export { default as TabBar } from './TabBar';
export { default as TitleBar } from './TitleBar';
>>>>>>> Stashed changes
