/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for Opening

export interface Opening {
  id: string;
  name: string;
  eco_code: string;
  moves: string;
  description: string;
  popularity_score: number;
  difficulty_level: string;
  created_at: string;
  updated_at: string;
}

export interface OpeningCreate {
  // Properties needed for creating new Opening
  id: string;
  name: string;
  eco_code: string;
  moves: string;
  description: string;
  popularity_score: number;
  difficulty_level: string;
  created_at: string;
  updated_at: string;
}

export interface OpeningUpdate {
  // Properties that can be updated
  id: string;
  name: string;
  eco_code: string;
  moves: string;
  description: string;
  popularity_score: number;
  difficulty_level: string;
  created_at: string;
  updated_at: string;
}

export interface OpeningFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
