/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// GameControls.tsx - Game control buttons following SRP
// Single Responsibility: Handle game control actions (new game, settings, etc.)

import React from 'react';
import type { PieceColor } from '../../types';

interface GameControlsProps {
  /** Handler for new game action */
  onNewGame: () => void;
  /** Handler for flip board action */
  onFlipBoard: () => void;
  /** Handler for resign game action */
  onResign?: () => void;
  /** Handler for undo move action */
  onUndo?: () => void;
  /** Whether controls should be disabled */
  disabled?: boolean;
  /** Whether the game is currently active */
  isGameActive?: boolean;
  /** Current player color */
  playerColor?: PieceColor;
}

export const GameControls: React.FC<GameControlsProps> = ({
  onNewGame,
  onFlipBoard,
  onResign,
  onUndo,
  disabled = false,
  isGameActive = true,
  playerColor = 'white'
}) => {
  // Mobile-first responsive button styles
  const buttonBaseClass = "text-xs sm:text-sm px-2 py-1 sm:px-3 sm:py-1 rounded font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex-1 sm:flex-none min-w-0";

  return (
    <div className="flex flex-col sm:flex-row gap-1 sm:gap-2 w-full sm:w-auto">
      {/* Primary actions - always visible */}
      <div className="flex gap-1 sm:gap-2">
        <button
          onClick={onNewGame}
          disabled={disabled}
          className={`${buttonBaseClass} bg-primary text-primary-foreground hover:bg-primary/90 disabled:hover:bg-primary`}
          title="Start a new game"
        >
          <span className="hidden sm:inline">🔄 New Game</span>
          <span className="sm:hidden">🔄 New</span>
        </button>
        
        <button
          onClick={onFlipBoard}
          disabled={disabled}
          className={`${buttonBaseClass} bg-secondary text-secondary-foreground hover:bg-secondary/90 disabled:hover:bg-secondary`}
          title={`Switch to playing as ${playerColor === 'white' ? 'black' : 'white'}`}
        >
          <span className="hidden sm:inline">🔄 Flip</span>
          <span className="sm:hidden">🔄</span>
        </button>
      </div>
      
      {/* Secondary actions - stack on mobile */}
      {(onUndo || onResign) && (
        <div className="flex gap-1 sm:gap-2">
          {onUndo && (
            <button
              onClick={onUndo}
              disabled={disabled || !isGameActive}
              className={`${buttonBaseClass} bg-accent text-accent-foreground hover:bg-accent/90 disabled:hover:bg-accent`}
              title="Undo last move"
            >
              <span className="hidden sm:inline">↶ Undo</span>
              <span className="sm:hidden">↶</span>
            </button>
          )}
          
          {onResign && (
            <button
              onClick={onResign}
              disabled={disabled || !isGameActive}
              className={`${buttonBaseClass} bg-destructive text-destructive-foreground hover:bg-destructive/90 disabled:hover:bg-destructive`}
              title="Resign this game"
            >
              <span className="hidden sm:inline">🏳️ Resign</span>
              <span className="sm:hidden">🏳️</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
};