/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for UserContentProgre

export interface UserContentProgre {
  id: string;
  user_id: string;
  content_id: string;
  status: string;
  progress_percentage: number;
  time_spent: number;
  completion_score: number;
  started_at: string;
  completed_at: string;
  last_accessed: string;
  notes: string;
  bookmarked: boolean;
  created_at: string;
  updated_at: string;
}

export interface UserContentProgreCreate {
  // Properties needed for creating new UserContentProgre
  id: string;
  user_id: string;
  content_id: string;
  status: string;
  progress_percentage: number;
  time_spent: number;
  completion_score: number;
  started_at: string;
  completed_at: string;
  last_accessed: string;
  notes: string;
  bookmarked: boolean;
  created_at: string;
  updated_at: string;
}

export interface UserContentProgreUpdate {
  // Properties that can be updated
  id: string;
  user_id: string;
  content_id: string;
  status: string;
  progress_percentage: number;
  time_spent: number;
  completion_score: number;
  started_at: string;
  completed_at: string;
  last_accessed: string;
  notes: string;
  bookmarked: boolean;
  created_at: string;
  updated_at: string;
}

export interface UserContentProgreFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
