/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import { useState } from 'react';
import { useAuth } from './authentication/useAuth';
import { useAuthStore } from '../stores/authStore';
import { sessionUtils } from '../utils';

export interface DemoLoginCredentials {
  email: string;
  password: string;
  name: string;
}

// Demo user credentials from the project plan
export const DEMO_USER_CREDENTIALS: DemoLoginCredentials = {
  email: 'chessdemo@example.com',
  password: 'ChessDemo2024',
  name: 'Demo User'
};

export interface UseDemoLoginReturn {
  loginWithDemo: () => Promise<void>;
  isLoading: boolean;
  error: string | null;
  isDemo: boolean;
}

/**
 * Hook for demo user auto-login functionality
 * Provides easy access to login with pre-configured demo credentials
 * Bypasses API when running in development mode for any environment
 */
export const useDemoLogin = (): UseDemoLoginReturn => {
  const { login, isLoading: loginLoading, error: loginError } = useAuth();
  const [isDemo, setIsDemo] = useState(false);
  const [localLoading, setLocalLoading] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);
  
  // Get auth store methods for bypass
  const setUser = useAuthStore((state) => state.setUser);
  const setToken = useAuthStore((state) => state.setToken);
  const setProgress = useAuthStore((state) => state.setProgress);
  const setLoading = useAuthStore((state) => state.setLoading);
  const setError = useAuthStore((state) => state.setError);

  // Always bypass API for demo login in development builds
  // Production builds should have this disabled via environment variable
  const isDevelopment = import.meta.env.DEV || 
                       import.meta.env.MODE === 'development' ||
                       !import.meta.env.PROD;
  
  console.log('🔍 Demo login environment check:', { 
    hostname: window.location.hostname,
    mode: import.meta.env.MODE,
    dev: import.meta.env.DEV,
    prod: import.meta.env.PROD,
    isDevelopment 
  });

  const loginWithDemo = async (): Promise<void> => {
    try {
      setIsDemo(true);
      setLocalError(null);

      if (isDevelopment) {
        // Bypass API call for development - simulate successful login
        setLocalLoading(true);
        setLoading(true);
        setError(null);

        // Simulate network delay
        await new Promise(resolve => setTimeout(resolve, 1000));

        // Create mock user data matching auth types
        const mockUser = {
          id: 'demo-user-1',
          username: 'demo_user',
          email: DEMO_USER_CREDENTIALS.email,
          firstName: 'Demo',
          lastName: 'User',
          avatar: undefined,
          createdAt: new Date(),
          updatedAt: new Date(),
          isVerified: true,
          role: 'user' as const,
          preferences: {
            theme: 'light' as const,
            notifications: {
              email: true,
              push: true,
              gameUpdates: true,
              promotions: false
            },
            privacy: {
              profileVisibility: 'public' as const,
              showOnlineStatus: true,
              allowFriendRequests: true
            },
            gameplay: {
              autoSave: true,
              showHints: true,
              difficultyLevel: 'intermediate' as const,
              preferredTimeControl: '10+0' as const
            }
          }
        };

        const mockToken = 'demo-token-dev-bypass';
        const mockProgress = {
          id: 'demo-progress-1',
          user_id: 'demo-user-1',
          puzzles_solved: 42,
          puzzles_correct: 35,
          current_streak: 3,
          best_streak: 8,
          total_time_spent: 1337,
          achievements_unlocked: JSON.stringify(['first_win', 'streak_3']),
          last_puzzle_date: new Date().toISOString(),
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        };

        // Store auth data
        sessionUtils.setSession(mockUser, mockToken);
        
        // Update store
        setUser(mockUser);
        setToken(mockToken);
        setProgress(mockProgress);
        setLoading(false);
        setLocalLoading(false);

        console.log('🚀 Demo login bypassed API (development mode)');
      } else {
        // Use normal API login for production
        await login({
          email: DEMO_USER_CREDENTIALS.email,
          password: DEMO_USER_CREDENTIALS.password,
        });
      }
    } catch (error) {
      setIsDemo(false);
      setLocalLoading(false);
      if (isDevelopment) {
        const errorMessage = 'Demo login bypass failed';
        setLocalError(errorMessage);
        setError(errorMessage);
        setLoading(false);
      }
      throw error;
    }
  };

  return {
    loginWithDemo,
    isLoading: isDevelopment ? localLoading : loginLoading,
    error: isDevelopment ? localError : loginError,
    isDemo,
  };
};