/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import React from 'react'
import { usePageInstructions } from '../../hooks/core/usePageInstructions'
import { usePageActions } from '../../hooks/core/usePageActions'
import { BrandedSplashPage } from '../../pages/splash/BrandedSplashPage'

const BrandedSplashPageWrapper: React.FC = () => {
  usePageInstructions('brandedsplash')
  usePageActions('brandedsplash')
  
  return <BrandedSplashPage />
}

export default BrandedSplashPageWrapper;
