/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

export interface User {
  id: string
  email: string
  username: string
  firstName?: string
  lastName?: string
  avatar?: string
  createdAt: Date
  updatedAt: Date
  isVerified: boolean
  role: UserRole
  preferences: UserPreferences
}

export interface UserProfile {
  id: string
  email: string
  username: string
  firstName?: string
  lastName?: string
  avatar?: string
  createdAt: Date
  updatedAt: Date
  isVerified: boolean
  role: UserRole
  preferences: UserPreferences
}

export interface UserPreferences {
  theme: 'light' | 'dark' | 'auto'
  notifications: NotificationSettings
  privacy: PrivacySettings
  gameplay: GameplaySettings
}

export interface NotificationSettings {
  email: boolean
  push: boolean
  gameUpdates: boolean
  promotions: boolean
}

export interface PrivacySettings {
  profileVisibility: 'public' | 'friends' | 'private'
  showOnlineStatus: boolean
  allowFriendRequests: boolean
}

export interface GameplaySettings {
  autoSave: boolean
  showHints: boolean
  difficultyLevel: 'beginner' | 'intermediate' | 'advanced' | 'expert'
  preferredTimeControl: '1+0' | '3+0' | '5+0' | '10+0' | '15+10' | '30+0'
}

export type UserRole = 'user' | 'premium' | 'admin' | 'moderator'

export interface UpdateProfileData {
  username?: string
  firstName?: string
  lastName?: string
  avatar?: string
  preferences?: Partial<UserPreferences>
}

export interface ChangePasswordData {
  currentPassword: string
  newPassword: string
  confirmPassword: string
}

export interface UserStats {
  gamesPlayed: number
  gamesWon: number
  gamesLost: number
  gamesDraw: number
  currentRating: number
  highestRating: number
  puzzlesSolved: number
  totalPlayTime: number // in minutes
}

export interface UserSession {
  id: string
  userId: string
  deviceInfo: string
  ipAddress: string
  location?: string
  createdAt: Date
  lastActive: Date
  isActive: boolean
}

// API Response types
export interface UserManagementResponse<T = any> {
  success: boolean
  data?: T
  message?: string
  errors?: string[]
}

export interface PaginatedUsersResponse {
  users: UserProfile[]
  total: number
  page: number
  limit: number
  hasNextPage: boolean
  hasPrevPage: boolean
}

// Error types
export interface UserManagementError {
  message: string
  code: string
  statusCode?: number
  name: string
}