/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import { SafeBackgroundEffectsRenderer } from '../background-effects/BackgroundEffectsRenderer'

interface BackgroundEffectsProps {
  className?: string
}

/**
 * Background Effects Component
 * Simplified wrapper around BackgroundEffectsRenderer
 * Maintains backward compatibility with existing AppLayout integration
 */
export function BackgroundEffects({ className = '' }: BackgroundEffectsProps) {
  return <SafeBackgroundEffectsRenderer className={className} />
}