/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useTestingActions } from "../../hooks/testing/useTestingActions";
import { TestingMainPage } from "./TestingMainPage";

import { MobileTestingMainPage } from "./MobileTestingMainPage";
// Child imports will be added here when children are created

interface TestingPageProps {
  // Add props as needed
}

export const TestingPage: React.FC<TestingPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  const isMobile = useIsMobile();
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("testing");
  usePageActions("testing");
  
  // Use parent actions hook for navigation methods
  useTestingActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = isMobile ? MobileTestingMainPage : TestingMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
  // Child routing logic will be added here when children are created
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="testing"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};