"""
Export Tracker Module - Prevents recursive processing of generated index files
"""
import re
from typing import Set, Dict, Optional
from pathlib import Path


class ExportTracker:
    """Tracks processed exports and detects generated index files to prevent feedback loops."""
    
    def __init__(self):
        self.processed_files: Set[str] = set()
        self.generated_exports: Dict[str, Set[str]] = {}
        self.source_exports: Dict[str, Set[str]] = {}
        
    def is_generated_index_file(self, file_path: str, content: str) -> bool:
        """
        Detect if an index file was generated by our tool.
        
        Args:
            file_path: Path to the file being analyzed
            content: Content of the file
            
        Returns:
            True if this is a generated index file that should be skipped
        """
        import logging
        logger = logging.getLogger(__name__)
        
        # Check for our auto-generated comment
        if "// Auto-generated index file" in content:
            logger.debug(f"    🔍 Detected generated index file (auto-generated comment): {file_path}")
            return True
            
        # Check for our regenerate comment
        if "// Run index generator to regenerate" in content:
            logger.debug(f"    🔍 Detected generated index file (regenerate comment): {file_path}")
            return True
            
        # Check for recursive self-imports (./index patterns)
        recursive_patterns = [
            r"from\s+['\"]\.\/index['\"]",
            r"export.*from\s+['\"]\.\/index['\"]",
            r"export.*\{\s*\w+.*\}\s+from\s+['\"]\.\/index['\"]"
        ]
        
        for pattern in recursive_patterns:
            if re.search(pattern, content):
                return True
                
        # Check for aliased exports that look generated (like indexUser, authTypesUser)
        generated_alias_patterns = [
            r"export\s+type\s+\{\s*\w+\s+as\s+index\w+\s*\}",
            r"export\s+type\s+\{\s*\w+\s+as\s+\w+Types\w+\s*\}",
            r"export\s+type\s+\{\s*index\w+\s*\}"
        ]
        
        for pattern in generated_alias_patterns:
            if re.search(pattern, content):
                return True
                
        return False
        
    def should_skip_file(self, file_path: str, content: str) -> bool:
        """
        Determine if a file should be skipped during analysis.
        
        Args:
            file_path: Path to the file being analyzed
            content: Content of the file
            
        Returns:
            True if file should be skipped
        """
        # Always skip if already processed
        if file_path in self.processed_files:
            return True
            
        # Skip if it's a generated index file
        if self.is_generated_index_file(file_path, content):
            return True
            
        # Skip test, spec, and config files
        skip_patterns = [
            r'\.test\.',
            r'\.spec\.',
            r'\.d\.ts$',
            r'\.stories\.',
            r'\.config\.'
        ]
        
        for pattern in skip_patterns:
            if re.search(pattern, file_path):
                return True
                
        return False
        
    def is_source_index_file(self, file_path: str, content: str) -> bool:
        """
        Determine if an index file contains actual source exports (not generated).
        
        Args:
            file_path: Path to the file being analyzed
            content: Content of the file
            
        Returns:
            True if this is a source index file with actual exports
        """
        # If it's detected as generated, it's not a source file
        if self.is_generated_index_file(file_path, content):
            return False
            
        # Check if it's an index file
        if not file_path.endswith('/index.ts') and not file_path.endswith('\\index.ts'):
            return False
            
        # Look for actual type definitions (not just re-exports)
        source_patterns = [
            r'export\s+(interface|type|class|enum|const|function)',
            r'export\s+default\s+(interface|type|class|enum|const|function)',
            r'(interface|type|class|enum)\s+\w+.*\{',
        ]
        
        for pattern in source_patterns:
            if re.search(pattern, content):
                return True
                
        return False
        
    def register_file_processed(self, file_path: str, exports: Set[str], is_source: bool = False):
        """
        Register that a file has been processed.
        
        Args:
            file_path: Path to the processed file
            exports: Set of export names found in the file
            is_source: Whether this file contains source definitions
        """
        self.processed_files.add(file_path)
        
        if is_source:
            self.source_exports[file_path] = exports.copy()
        else:
            self.generated_exports[file_path] = exports.copy()
            
    def get_source_exports_for_directory(self, dir_path: str) -> Set[str]:
        """
        Get all source exports for a specific directory.
        
        Args:
            dir_path: Directory path to check
            
        Returns:
            Set of export names from source files in the directory
        """
        exports = set()
        for file_path, file_exports in self.source_exports.items():
            if dir_path in file_path:
                exports.update(file_exports)
        return exports
        
    def clear(self):
        """Clear all tracking data."""
        self.processed_files.clear()
        self.generated_exports.clear()
        self.source_exports.clear()
        
    def get_stats(self) -> Dict[str, int]:
        """Get statistics about processed files."""
        return {
            'total_processed': len(self.processed_files),
            'source_files': len(self.source_exports),
            'generated_files': len(self.generated_exports)
        }