/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for Game

export interface Game {
  id: string;
  user_id: string;
  ai_level: number;
  user_color: string;
  current_fen: string;
  pgn: string;
  status: string;
  result: string;
  time_control: string;
  started_at: string;
  completed_at: string;
  created_at: string;
  updated_at: string;
}

export interface GameCreate {
  // Properties needed for creating new Game
  id: string;
  user_id: string;
  ai_level: number;
  user_color: string;
  current_fen: string;
  pgn: string;
  status: string;
  result: string;
  time_control: string;
  started_at: string;
  completed_at: string;
  created_at: string;
  updated_at: string;
}

export interface GameUpdate {
  // Properties that can be updated
  id: string;
  user_id: string;
  ai_level: number;
  user_color: string;
  current_fen: string;
  pgn: string;
  status: string;
  result: string;
  time_control: string;
  started_at: string;
  completed_at: string;
  created_at: string;
  updated_at: string;
}

export interface GameFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
