/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for HistoricGame

export interface HistoricGame {
  id: string;
  white_player: string;
  black_player: string;
  white_rating: number;
  black_rating: number;
  tournament_name: string;
  tournament_year: number;
  opening_name: string;
  opening_eco: string;
  result: string;
  pgn: string;
  created_at: string;
  updated_at: string;
}

export interface HistoricGameCreate {
  // Properties needed for creating new HistoricGame
  id: string;
  white_player: string;
  black_player: string;
  white_rating: number;
  black_rating: number;
  tournament_name: string;
  tournament_year: number;
  opening_name: string;
  opening_eco: string;
  result: string;
  pgn: string;
  created_at: string;
  updated_at: string;
}

export interface HistoricGameUpdate {
  // Properties that can be updated
  id: string;
  white_player: string;
  black_player: string;
  white_rating: number;
  black_rating: number;
  tournament_name: string;
  tournament_year: number;
  opening_name: string;
  opening_eco: string;
  result: string;
  pgn: string;
  created_at: string;
  updated_at: string;
}

export interface HistoricGameFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
