/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useChessActions } from "../../hooks/chess/useChessActions";
import { ChessMainPage } from "./ChessMainPage";

import { MobileChessMainPage } from "./MobileChessMainPage";
import { PlayChessPageWrapper } from "../../components/chess/PlayChessPageWrapper";
import { PlayPuzzlesPageWrapper } from "../../components/chess/PlayPuzzlesPageWrapper";

interface ChessPageProps {
  // Add props as needed
}

export const ChessPage: React.FC<ChessPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  const isMobile = useIsMobile();
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("chess");
  usePageActions("chess");
  
  // Use parent actions hook for navigation methods
  useChessActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = isMobile ? MobileChessMainPage : ChessMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "playchess") {
    CurrentPageComponent = PlayChessPageWrapper;
  } else  if (currentChildPage === "playpuzzles") {
    CurrentPageComponent = PlayPuzzlesPageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="chess"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};