/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export * from './ChessMainPage';
export * from './ChessPage';
export * from './MobileChessMainPage';
export * from './MobilePlayChessPage';
export * from './MobilePlayPuzzlesPage';
export * from './PlayChessPage';
export * from './PlayPuzzlesPage';