<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './puzzle.types';

export { AUDIO_FEEDBACK_PATTERNS, DEFAULT_CHESS_BOARD_AUDIO_CONFIG, DEFAULT_AUDIO_TIMING, CHESS_BOARD_AUDIO_PROFILES } from './audio';
export type { ElementDetectionResult, UIExclusionConfig, GlobalClickHandler, AudioFeedbackContext, UIInteractionConfig, AudioFeedbackTiming, AudioFeedbackPattern, ChessBoardAudioEvents, GlobalUIAudioService, AudioFeedbackDecision, GlobalUIAudioConfigUpdate, GlobalUIAudioConfig, ChessBoardInteractionType, UISoundType, UIInteractionType, UIElementSelector, ChessBoardAudioConfig, ComponentAudioConfig, AudioFeedbackIntensity, MoveAudioContext } from './audio';
export type { UseForgotPasswordReturn, UserProgress, AuthGuardProps, MeResponse, AuthActions, AuthErrorType, UseAuthReturn, ProtectedRouteProps, LoginRequest, AuthStorage, LoginResponse, ForgotPasswordRequest, AuthFormState, AuthContextValue, AuthResponse, AuthState, User, ResetPasswordRequest, ChangePasswordRequest, TokenInfo, RegisterRequest, AuthConfig, AuthError, AuthApiClient, UseLoginReturn, UseRegisterReturn, TokenVerificationResponse, FormValidationError, UpdateProfileRequest, VerifyTokenRequest } from './auth';
export { MOBILE_TOUCH_THRESHOLDS, MOBILE_BOARD_SIZE_PRESETS, DEFAULT_MOBILE_CHESS_CONFIG } from './chess';
export type { MobileChessConfig, PieceType, PlayGameState, MobileBoardState, ComputerOpponentStatus, MobileBoardDimensions, ChessGameState, ChessPosition, ChessPiece, ComputerThinkingState, ComputerMoveAnalysis, PlayGameActions, PieceColor, GameSession, ChessMoveInput, ChessMove, CastlingRights, PlayGameMode, File, GameSettings, GameResult, ChessPositionObject, ComputerMoveResult, PlayGameResult, Rank, GameResultType, MobilePieceAnimation, ChessMoveResult, PlayerInfo, ComputerDifficulty, MobileSquareState, MobileTouchEvent, MobileChessInteraction, MobileChessGameState, ComputerOpponentConfig, GameMoveRecord, ComputerMoveRequest, WrapperPiece, MobileChessMoveResult } from './chess';
export type { ChessboardProps, BoardProps, PieceProps, PlayChessboardProps, IBackgroundEffectsService, ActionSheetAction, BackgroundEffectProps, SquareProps, DraggedPieceProps, ActionSheetContainerProps, BackgroundEffectConfig, ActionSheetProps, BackgroundEffectVariant } from './core';
export type { PlayComponentSize, MoveHandler, MoveHistoryProps, GameStatusBarProps, AudioDemoHook, CodeSnippet, GameControlsProps, PlayComponentAnimation, ExclusionExample, BasePlayComponentProps, AudioDemoState, DemoButtonExample, AudioDemoActions, DragTestingHook, PlaySettingsProps, UITestNavigationState, DemoSection, UITestRoute, UITestNavigationHook, AudioDemoConfiguration, DragTestState, DifficultyLevelProps, DragTestConfiguration, ComputerThinkingProps, PlayerStatusProps, GameResultModalProps, DragTestActions, UITestNavigationActions, PlayComponentTheme } from './ui';
=======
// Auto-generated barrel export for types
// Generated by AdvancedBarrelGenerator

// Named exports only

// Subdirectory exports
export * from './audio';
export type * from './auth';
export type * from './authentication';
export * from './chess';
export type * from './chess-theory';
export type * from './core';
export type * from './gameplay';
export type * from './learning';
export type * as puzzles from './puzzles';
export type * from './ui';
export type * as userManagement from './user-management';
>>>>>>> Stashed changes
