#!/usr/bin/env python3
"""
Test suite for the Validation module.
"""

import unittest
import tempfile
from pathlib import Path
import sys

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from modules.validation import ProjectValidator, ValidationResult, ValidationReport, ValidationError
from modules.template_engine import TemplateEngine
from modules.config import PageConfig, ProjectCapabilities, GenerationContext


class TestProjectValidator(unittest.TestCase):
    """Test cases for ProjectValidator."""
    
    def setup_method(self):
        """Set up test fixtures."""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.templates_dir = self.temp_dir / "templates"
        
        # Create template structure
        self.templates_dir.mkdir(parents=True)
        self._create_basic_templates()
        
        self.validator = ProjectValidator(
            frontend_root=self.temp_dir,
            templates_dir=self.templates_dir
        )
    
    def teardown_method(self):
        """Clean up test fixtures."""
        import shutil
        if self.temp_dir.exists():
            shutil.rmtree(self.temp_dir)
    
    def _create_basic_templates(self):
        """Create basic template structure for testing."""
        (self.templates_dir / "pages").mkdir()
        (self.templates_dir / "components").mkdir()
        
        # Create a basic template
        test_template = self.templates_dir / "pages" / "test.template"
        test_template.write_text("const {{PAGE_NAME}} = () => <div>{{CONTENT}}</div>;")
    
    def _create_basic_project_structure(self):
        """Create basic project structure for testing."""
        # Create src directories
        src_dir = self.temp_dir / "src"
        (src_dir / "pages").mkdir(parents=True)
        (src_dir / "components").mkdir(parents=True)
        (src_dir / "hooks" / "core").mkdir(parents=True)
        (src_dir / "constants").mkdir(parents=True)
        (src_dir / "services").mkdir(parents=True)
        
        # Create package.json
        package_json = self.temp_dir / "package.json"
        package_json.write_text('{"name": "test-project", "dependencies": {}}')
        
        return src_dir
    
    def test_validation_result_creation(self):
        """Test ValidationResult dataclass."""
        result = ValidationResult(
            category="test",
            item="test_item",
            status=True,
            message="Test passed",
            severity="info"
        )
        
        self.assertEqual(result.category, "test")
        self.assertEqual(result.item, "test_item")
        self.assertTrue(result.status)
        self.assertEqual(result.message, "Test passed")
        self.assertEqual(result.severity, "info")
    
    def test_validation_report_creation(self):
        """Test ValidationReport dataclass."""
        results = [
            ValidationResult("test1", "item1", True),
            ValidationResult("test2", "item2", False)
        ]
        
        summary = {"passed": 1, "failed": 1}
        
        report = ValidationReport(
            results=results,
            summary=summary,
            passed=False
        )
        
        self.assertEqual(len(report.results), 2)
        self.assertEqual(report.summary["passed"], 1)
        self.assertFalse(report.passed)
    
    def test_validate_project_structure(self):
        """Test project structure validation."""
        # Test with missing structure
        report = self.validator.validate_project_structure()
        self.assertFalse(report.passed)
        
        # Create proper structure
        self._create_basic_project_structure()
        
        # Test with proper structure
        report = self.validator.validate_project_structure()
        self.assertTrue(report.passed)
    
    def test_validate_templates(self):
        """Test template validation."""
        report = self.validator.validate_templates()
        
        # Should pass with basic templates created
        self.assertTrue(report.passed)
        
        # Check that it found some templates
        template_results = [r for r in report.results if r.category == "template"]
        self.assertTrue(len(template_results) > 0)
    
    def test_validate_generated_files(self):
        """Test validation of generated files."""
        src_dir = self._create_basic_project_structure()
        
        # Create some mock generated files with proper headers
        generated_file = src_dir / "pages" / "TestPage.tsx"
        generated_content = """
// WARNING: GENERATED CODE - DO NOT MODIFY
// Generated by: TestGenerator
// Source: test_validation.py

import React from 'react';

const TestPage = () => {
  return <div>Test</div>;
};

export default TestPage;
""".strip()
        
        generated_file.write_text(generated_content)
        
        report = self.validator.validate_generated_files()
        
        # Should find and validate the generated file
        generated_results = [r for r in report.results if r.category == "generated_file"]
        self.assertTrue(len(generated_results) > 0)
    
    def test_validate_routing_consistency(self):
        """Test routing consistency validation."""
        src_dir = self._create_basic_project_structure()
        
        # Create a parent page with routing
        settings_dir = src_dir / "pages" / "settings"
        settings_dir.mkdir()
        
        parent_file = settings_dir / "SettingsPage.tsx"
        parent_file.write_text("""
const SettingsPage = () => {
    switch (route) {
        case 'main':
            return <SettingsMainPage />;
        case 'profile':
            return <ProfileWrapper />;
        default:
            return <div>Not Found</div>;
    }
};
""".strip())
        
        # Create child file
        child_file = settings_dir / "Profile.tsx"
        child_file.write_text("const Profile = () => <div>Profile</div>;")
        
        report = self.validator.validate_routing_consistency()
        
        # Should detect routing
        routing_results = [r for r in report.results if r.category == "routing"]
        self.assertTrue(len(routing_results) > 0)
    
    def test_comprehensive_validation(self):
        """Test comprehensive validation that runs all checks."""
        self._create_basic_project_structure()
        
        report = self.validator.run_comprehensive_validation()
        
        # Should have results from multiple categories
        categories = set(r.category for r in report.results)
        expected_categories = {"project_structure", "template", "generated_file", "routing"}
        
        # Should have at least some of the expected categories
        self.assertTrue(len(categories.intersection(expected_categories)) > 0)
    
    def test_validation_with_config_context(self):
        """Test validation with specific generation context."""
        config = PageConfig(name="TestPage", parent="TestParent")
        capabilities = ProjectCapabilities(
            has_page_hooks=True,
            has_mobile_hook=False,
            has_data_table=True
        )
        
        context = GenerationContext(
            config=config,
            capabilities=capabilities,
            frontend_root=self.temp_dir,
            templates_dir=self.templates_dir
        )
        
        report = self.validator.validate_generation_context(context)
        
        # Should validate the context
        self.assertIsInstance(report, ValidationReport)
        
        context_results = [r for r in report.results if r.category == "generation_context"]
        self.assertTrue(len(context_results) > 0)
    
    def test_get_validation_summary(self):
        """Test getting validation summary."""
        self._create_basic_project_structure()
        
        summary = self.validator.get_validation_summary()
        
        # Should contain summary information
        self.assertIn('total_checks', summary)
        self.assertIn('passed_checks', summary)
        self.assertIn('failed_checks', summary)
        self.assertIn('categories', summary)
    
    def test_validation_error_handling(self):
        """Test validation error handling for critical failures."""
        # Test with non-existent frontend root
        with self.assertRaises(ValidationError):
            ProjectValidator(
                frontend_root=Path("/nonexistent/path"),
                templates_dir=self.templates_dir
            )


if __name__ == '__main__':
    unittest.main()