/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { Pool } from 'pg';

export class Database {
  private static instance: Database;
  private pool: Pool;

  private constructor() {
    this.pool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
      max: 5,
      min: 1,
      idleTimeoutMillis: 10000,
      connectionTimeoutMillis: 10000,
      allowExitOnIdle: false,
      keepAlive: true,
      keepAliveInitialDelayMillis: 10000
    });

    this.pool.on('error', (err) => {
      console.error('❌ Database pool error:', err);
      if (err.message && err.message.includes('termination')) {
        console.log('🔄 Database connection terminated, pool will handle reconnection');
      }
    });

    this.pool.on('connect', (client) => {
      console.log('🔗 Database client connected');
      client.query('SET statement_timeout = 30000');
    });

    this.pool.on('remove', (client) => {
      console.log('🔌 Database client disconnected');
    });
  }

  public static getInstance(): Database {
    if (!Database.instance) {
      Database.instance = new Database();
    }
    return Database.instance;
  }

  async query(text: string, params?: any[]) {
    let client;
    try {
      client = await this.pool.connect();
      const result = await client.query(text, params);
      return result;
    } catch (error) {
      console.error('❌ Database query error:', error);
      if (error.message && error.message.includes('termination')) {
        console.log('🔄 Query failed due to connection termination, retrying...');
        try {
          const newClient = await this.pool.connect();
          const result = await newClient.query(text, params);
          newClient.release();
          return result;
        } catch (retryError) {
          console.error('❌ Retry also failed:', retryError);
          throw retryError;
        }
      }
      throw error;
    } finally {
      if (client) {
        client.release();
      }
    }
  }

  async getPoolInfo() {
    return {
      totalCount: this.pool.totalCount,
      idleCount: this.pool.idleCount,
      waitingCount: this.pool.waitingCount
    };
  }

  async close() {
    await this.pool.end();
  }
}

export const db = Database.getInstance();
export default Database;