/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for Puzzle

export interface Puzzle {
  id: string;
  fen: string;
  solution_moves: string;
  themes: any;
  rating: number;
  description: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleCreate {
  // Properties needed for creating new Puzzle
  id: string;
  fen: string;
  solution_moves: string;
  themes: any;
  rating: number;
  description: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleUpdate {
  // Properties that can be updated
  id: string;
  fen: string;
  solution_moves: string;
  themes: any;
  rating: number;
  description: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
