/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for PuzzleSource

export interface PuzzleSource {
  id: string;
  source_id: string;
  name: string;
  description: string;
  total_puzzles: number;
  average_rating: number;
  is_active: boolean;
  attribution: string;
  license: string;
  url: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleSourceCreate {
  // Properties needed for creating new PuzzleSource
  id: string;
  source_id: string;
  name: string;
  description: string;
  total_puzzles: number;
  average_rating: number;
  is_active: boolean;
  attribution: string;
  license: string;
  url: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleSourceUpdate {
  // Properties that can be updated
  id: string;
  source_id: string;
  name: string;
  description: string;
  total_puzzles: number;
  average_rating: number;
  is_active: boolean;
  attribution: string;
  license: string;
  url: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleSourceFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
