/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for PuzzleAttempt

export interface PuzzleAttempt {
  id: string;
  user_id: string;
  puzzle_id: string;
  moves: string;
  correct: boolean;
  time_taken: number;
  hints_used: number;
  rating_change: number;
  attempted_at: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleAttemptCreate {
  // Properties needed for creating new PuzzleAttempt
  id: string;
  user_id: string;
  puzzle_id: string;
  moves: string;
  correct: boolean;
  time_taken: number;
  hints_used: number;
  rating_change: number;
  attempted_at: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleAttemptUpdate {
  // Properties that can be updated
  id: string;
  user_id: string;
  puzzle_id: string;
  moves: string;
  correct: boolean;
  time_taken: number;
  hints_used: number;
  rating_change: number;
  attempted_at: string;
  created_at: string;
  updated_at: string;
}

export interface PuzzleAttemptFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
