/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { AchievementResponse, CreateAchievementRequest, UpdateAchievementRequest } from '../models/Achievement';

export class AchievementService {
  private db = Database.getInstance();

async getAchievementById(id: string): Promise<AchievementResponse> {
    const result = await this.db.query('SELECT * FROM achievements WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('Achievement not found');
    
    return this.formatAchievementResponse(result.rows[0]);
  }

async getAllAchievements(): Promise<AchievementResponse[]> {
    const result = await this.db.query('SELECT * FROM achievements ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatAchievementResponse(row));
  }

async listAchievements(): Promise<AchievementResponse[]> {
    const result = await this.db.query('SELECT * FROM achievements ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatAchievementResponse(row));
  }

async updateAchievement(id: string, data: UpdateAchievementRequest): Promise<AchievementResponse> {
    const { name, description, category, icon, points, difficulty, requirements } = data;
    const result = await this.db.query(`
      UPDATE achievements 
      SET name = $2, description = $3, category = $4, icon = $5, points = $6, difficulty = $7, requirements = $8, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, name, description, category, icon, points, difficulty, requirements]);
    
    if (!result.rows.length) throw new Error('Achievement not found');
    return this.formatAchievementResponse(result.rows[0]);
  }

async deleteAchievement(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM achievements WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('Achievement not found');
  }

async createAchievement(data: CreateAchievementRequest): Promise<AchievementResponse> {
    const { name, description, category, icon, points, difficulty, requirements } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO achievements (id, name, description, category, icon, points, difficulty, requirements, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
      RETURNING *
    `, [id, name, description, category, icon, points, difficulty, requirements]);
    
    return this.formatAchievementResponse(result.rows[0]);
  }

private formatAchievementResponse(row: any): AchievementResponse {
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      category: row.category,
      icon: row.icon,
      points: row.points,
      difficulty: row.difficulty,
      requirements: row.requirements,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}