/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { ContentResponse, CreateContentRequest, UpdateContentRequest } from '../models/Content';

export class ContentService {
  private db = Database.getInstance();

async updateContent(id: string, data: UpdateContentRequest): Promise<ContentResponse> {
    const { title, content_type, parent_id, order_index, description, content_body, difficulty_level, estimated_duration, category, objectives, prerequisites, is_published, version } = data;
    const result = await this.db.query(`
      UPDATE content 
      SET title = $2, content_type = $3, parent_id = $4, order_index = $5, description = $6, content_body = $7, difficulty_level = $8, estimated_duration = $9, category = $10, objectives = $11, prerequisites = $12, is_published = $13, version = $14, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, title, content_type, parent_id, order_index, description, content_body, difficulty_level, estimated_duration, category, objectives, prerequisites, is_published, version]);
    
    if (!result.rows.length) throw new Error('Content not found');
    return this.formatContentResponse(result.rows[0]);
  }

async listContents(): Promise<ContentResponse[]> {
    const result = await this.db.query('SELECT * FROM content ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatContentResponse(row));
  }

async getAllContent(): Promise<ContentResponse[]> {
    const result = await this.db.query('SELECT * FROM content ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatContentResponse(row));
  }

async getContentById(id: string): Promise<ContentResponse> {
    const result = await this.db.query('SELECT * FROM content WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('Content not found');
    
    return this.formatContentResponse(result.rows[0]);
  }

async deleteContent(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM content WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('Content not found');
  }

async createContent(data: CreateContentRequest): Promise<ContentResponse> {
    const { title, content_type, parent_id, order_index, description, content_body, difficulty_level, estimated_duration, category, objectives, prerequisites, is_published, version } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO content (id, title, content_type, parent_id, order_index, description, content_body, difficulty_level, estimated_duration, category, objectives, prerequisites, is_published, version, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW(), NOW())
      RETURNING *
    `, [id, title, content_type, parent_id, order_index, description, content_body, difficulty_level, estimated_duration, category, objectives, prerequisites, is_published, version]);
    
    return this.formatContentResponse(result.rows[0]);
  }

private formatContentResponse(row: any): ContentResponse {
    return {
      id: row.id,
      title: row.title,
      content_type: row.content_type,
      parent_id: row.parent_id,
      order_index: row.order_index,
      description: row.description,
      content_body: row.content_body,
      difficulty_level: row.difficulty_level,
      estimated_duration: row.estimated_duration,
      category: row.category,
      objectives: row.objectives,
      prerequisites: row.prerequisites,
      is_published: row.is_published,
      version: row.version,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}