/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { HistoricGameResponse, CreateHistoricGameRequest, UpdateHistoricGameRequest } from '../models/HistoricGame';

export class HistoricGameService {
  private db = Database.getInstance();

async getAllHistoric_games(): Promise<HistoricGameResponse[]> {
    const result = await this.db.query('SELECT * FROM historic_games ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatHistoricGameResponse(row));
  }

async listHistoricGames(): Promise<HistoricGameResponse[]> {
    const result = await this.db.query('SELECT * FROM historic_games ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatHistoricGameResponse(row));
  }

async createHistoricGame(data: CreateHistoricGameRequest): Promise<HistoricGameResponse> {
    const { white_player, black_player, white_rating, black_rating, tournament_name, tournament_year, opening_name, opening_eco, result: resultData, pgn } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO historic_games (id, white_player, black_player, white_rating, black_rating, tournament_name, tournament_year, opening_name, opening_eco, result, pgn, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
      RETURNING *
    `, [id, white_player, black_player, white_rating, black_rating, tournament_name, tournament_year, opening_name, opening_eco, resultData, pgn]);
    
    return this.formatHistoricGameResponse(result.rows[0]);
  }

async getHistoricGameById(id: string): Promise<HistoricGameResponse> {
    const result = await this.db.query('SELECT * FROM historic_games WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('HistoricGame not found');
    
    return this.formatHistoricGameResponse(result.rows[0]);
  }

async updateHistoricGame(id: string, data: UpdateHistoricGameRequest): Promise<HistoricGameResponse> {
    const { white_player, black_player, white_rating, black_rating, tournament_name, tournament_year, opening_name, opening_eco, result: resultData, pgn } = data;
    const result = await this.db.query(`
      UPDATE historic_games 
      SET white_player = $2, black_player = $3, white_rating = $4, black_rating = $5, tournament_name = $6, tournament_year = $7, opening_name = $8, opening_eco = $9, result = $10, pgn = $11, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, white_player, black_player, white_rating, black_rating, tournament_name, tournament_year, opening_name, opening_eco, resultData, pgn]);
    
    if (!result.rows.length) throw new Error('HistoricGame not found');
    return this.formatHistoricGameResponse(result.rows[0]);
  }

async deleteHistoricGame(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM historic_games WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('HistoricGame not found');
  }

private formatHistoricGameResponse(row: any): HistoricGameResponse {
    return {
      id: row.id,
      white_player: row.white_player,
      black_player: row.black_player,
      white_rating: row.white_rating,
      black_rating: row.black_rating,
      tournament_name: row.tournament_name,
      tournament_year: row.tournament_year,
      opening_name: row.opening_name,
      opening_eco: row.opening_eco,
      result: row.result,
      pgn: row.pgn,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}