/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { OpeningResponse, CreateOpeningRequest, UpdateOpeningRequest } from '../models/Opening';

export class OpeningService {
  private db = Database.getInstance();

async deleteOpening(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM openings WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('Opening not found');
  }

async getOpeningById(id: string): Promise<OpeningResponse> {
    const result = await this.db.query('SELECT * FROM openings WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('Opening not found');
    
    return this.formatOpeningResponse(result.rows[0]);
  }

async updateOpening(id: string, data: UpdateOpeningRequest): Promise<OpeningResponse> {
    const { name, eco_code, moves, description, popularity_score, difficulty_level } = data;
    const result = await this.db.query(`
      UPDATE openings 
      SET name = $2, eco_code = $3, moves = $4, description = $5, popularity_score = $6, difficulty_level = $7, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, name, eco_code, moves, description, popularity_score, difficulty_level]);
    
    if (!result.rows.length) throw new Error('Opening not found');
    return this.formatOpeningResponse(result.rows[0]);
  }

async createOpening(data: CreateOpeningRequest): Promise<OpeningResponse> {
    const { name, eco_code, moves, description, popularity_score, difficulty_level } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO openings (id, name, eco_code, moves, description, popularity_score, difficulty_level, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
      RETURNING *
    `, [id, name, eco_code, moves, description, popularity_score, difficulty_level]);
    
    return this.formatOpeningResponse(result.rows[0]);
  }

async getAllOpenings(): Promise<OpeningResponse[]> {
    const result = await this.db.query('SELECT * FROM openings ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatOpeningResponse(row));
  }

async listOpenings(): Promise<OpeningResponse[]> {
    const result = await this.db.query('SELECT * FROM openings ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatOpeningResponse(row));
  }

private formatOpeningResponse(row: any): OpeningResponse {
    return {
      id: row.id,
      name: row.name,
      eco_code: row.eco_code,
      moves: row.moves,
      description: row.description,
      popularity_score: row.popularity_score,
      difficulty_level: row.difficulty_level,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}