/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { PuzzleAttemptResponse, CreatePuzzleAttemptRequest, UpdatePuzzleAttemptRequest } from '../models/PuzzleAttempt';

export class PuzzleAttemptService {
  private db = Database.getInstance();

async createPuzzleAttempt(data: CreatePuzzleAttemptRequest): Promise<PuzzleAttemptResponse> {
    const { user_id, puzzle_id, moves, correct, time_taken, hints_used, rating_change, attempted_at } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO puzzle_attempts (id, user_id, puzzle_id, moves, correct, time_taken, hints_used, rating_change, attempted_at, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
      RETURNING *
    `, [id, user_id, puzzle_id, moves, correct, time_taken, hints_used, rating_change, attempted_at]);
    
    return this.formatPuzzleAttemptResponse(result.rows[0]);
  }

async updatePuzzleAttempt(id: string, data: UpdatePuzzleAttemptRequest): Promise<PuzzleAttemptResponse> {
    const { user_id, puzzle_id, moves, correct, time_taken, hints_used, rating_change, attempted_at } = data;
    const result = await this.db.query(`
      UPDATE puzzle_attempts 
      SET user_id = $2, puzzle_id = $3, moves = $4, correct = $5, time_taken = $6, hints_used = $7, rating_change = $8, attempted_at = $9, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, user_id, puzzle_id, moves, correct, time_taken, hints_used, rating_change, attempted_at]);
    
    if (!result.rows.length) throw new Error('PuzzleAttempt not found');
    return this.formatPuzzleAttemptResponse(result.rows[0]);
  }

async getAllPuzzle_attempts(): Promise<PuzzleAttemptResponse[]> {
    const result = await this.db.query('SELECT * FROM puzzle_attempts ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatPuzzleAttemptResponse(row));
  }

async getPuzzleAttemptById(id: string): Promise<PuzzleAttemptResponse> {
    const result = await this.db.query('SELECT * FROM puzzle_attempts WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('PuzzleAttempt not found');
    
    return this.formatPuzzleAttemptResponse(result.rows[0]);
  }

async deletePuzzleAttempt(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM puzzle_attempts WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('PuzzleAttempt not found');
  }

async listPuzzleAttempts(): Promise<PuzzleAttemptResponse[]> {
    const result = await this.db.query('SELECT * FROM puzzle_attempts ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatPuzzleAttemptResponse(row));
  }

private formatPuzzleAttemptResponse(row: any): PuzzleAttemptResponse {
    return {
      id: row.id,
      user_id: row.user_id,
      puzzle_id: row.puzzle_id,
      moves: row.moves,
      correct: row.correct,
      time_taken: row.time_taken,
      hints_used: row.hints_used,
      rating_change: row.rating_change,
      attempted_at: row.attempted_at,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}