/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { PuzzleSourceResponse, CreatePuzzleSourceRequest, UpdatePuzzleSourceRequest } from '../models/PuzzleSource';

export class PuzzleSourceService {
  private db = Database.getInstance();

async getAllPuzzle_sources(): Promise<PuzzleSourceResponse[]> {
    const result = await this.db.query('SELECT * FROM puzzle_sources ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatPuzzleSourceResponse(row));
  }

async createPuzzleSource(data: CreatePuzzleSourceRequest): Promise<PuzzleSourceResponse> {
    const { source_id, name, description, total_puzzles, average_rating, is_active, attribution, license, url } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO puzzle_sources (id, source_id, name, description, total_puzzles, average_rating, is_active, attribution, license, url, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
      RETURNING *
    `, [id, source_id, name, description, total_puzzles, average_rating, is_active, attribution, license, url]);
    
    return this.formatPuzzleSourceResponse(result.rows[0]);
  }

async getPuzzleSourceById(id: string): Promise<PuzzleSourceResponse> {
    const result = await this.db.query('SELECT * FROM puzzle_sources WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('PuzzleSource not found');
    
    return this.formatPuzzleSourceResponse(result.rows[0]);
  }

async deletePuzzleSource(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM puzzle_sources WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('PuzzleSource not found');
  }

async updatePuzzleSource(id: string, data: UpdatePuzzleSourceRequest): Promise<PuzzleSourceResponse> {
    const { source_id, name, description, total_puzzles, average_rating, is_active, attribution, license, url } = data;
    const result = await this.db.query(`
      UPDATE puzzle_sources 
      SET source_id = $2, name = $3, description = $4, total_puzzles = $5, average_rating = $6, is_active = $7, attribution = $8, license = $9, url = $10, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, source_id, name, description, total_puzzles, average_rating, is_active, attribution, license, url]);
    
    if (!result.rows.length) throw new Error('PuzzleSource not found');
    return this.formatPuzzleSourceResponse(result.rows[0]);
  }

async listPuzzleSources(): Promise<PuzzleSourceResponse[]> {
    const result = await this.db.query('SELECT * FROM puzzle_sources ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatPuzzleSourceResponse(row));
  }

private formatPuzzleSourceResponse(row: any): PuzzleSourceResponse {
    return {
      id: row.id,
      source_id: row.source_id,
      name: row.name,
      description: row.description,
      total_puzzles: row.total_puzzles,
      average_rating: row.average_rating,
      is_active: row.is_active,
      attribution: row.attribution,
      license: row.license,
      url: row.url,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}