/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserProfileResponse, CreateUserProfileRequest, UpdateUserProfileRequest } from '../models/UserProfile';

export class UserProfileService {
  private db = Database.getInstance();

async getAllUser_profiles(): Promise<UserProfileResponse[]> {
    const result = await this.db.query('SELECT * FROM user_profiles ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserProfileResponse(row));
  }

async updateUserProfile(id: string, data: UpdateUserProfileRequest): Promise<UserProfileResponse> {
    const { user_id, display_name, avatar_url, bio, country, timezone } = data;
    const result = await this.db.query(`
      UPDATE user_profiles 
      SET user_id = $2, display_name = $3, avatar_url = $4, bio = $5, country = $6, timezone = $7, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, user_id, display_name, avatar_url, bio, country, timezone]);
    
    if (!result.rows.length) throw new Error('UserProfile not found');
    return this.formatUserProfileResponse(result.rows[0]);
  }

async deleteUserProfile(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM user_profiles WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('UserProfile not found');
  }

async createUserProfile(data: CreateUserProfileRequest): Promise<UserProfileResponse> {
    const { user_id, display_name, avatar_url, bio, country, timezone } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO user_profiles (id, user_id, display_name, avatar_url, bio, country, timezone, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
      RETURNING *
    `, [id, user_id, display_name, avatar_url, bio, country, timezone]);
    
    return this.formatUserProfileResponse(result.rows[0]);
  }

async listUserProfiles(): Promise<UserProfileResponse[]> {
    const result = await this.db.query('SELECT * FROM user_profiles ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserProfileResponse(row));
  }

async getUserProfileById(id: string): Promise<UserProfileResponse> {
    const result = await this.db.query('SELECT * FROM user_profiles WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('UserProfile not found');
    
    return this.formatUserProfileResponse(result.rows[0]);
  }

private formatUserProfileResponse(row: any): UserProfileResponse {
    return {
      id: row.id,
      user_id: row.user_id,
      display_name: row.display_name,
      avatar_url: row.avatar_url,
      bio: row.bio,
      country: row.country,
      timezone: row.timezone,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}