/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserAchievementResponse, CreateUserAchievementRequest, UpdateUserAchievementRequest } from '../models/UserAchievement';

export class UserAchievementService {
  private db = Database.getInstance();

async createUserAchievement(data: CreateUserAchievementRequest): Promise<UserAchievementResponse> {
    const { user_id, achievement_id, earned_at, progress } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO user_achievements (id, user_id, achievement_id, earned_at, progress, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
      RETURNING *
    `, [id, user_id, achievement_id, earned_at, progress]);
    
    return this.formatUserAchievementResponse(result.rows[0]);
  }

async deleteUserAchievement(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM user_achievements WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('UserAchievement not found');
  }

async updateUserAchievement(id: string, data: UpdateUserAchievementRequest): Promise<UserAchievementResponse> {
    const { user_id, achievement_id, earned_at, progress } = data;
    const result = await this.db.query(`
      UPDATE user_achievements 
      SET user_id = $2, achievement_id = $3, earned_at = $4, progress = $5, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, user_id, achievement_id, earned_at, progress]);
    
    if (!result.rows.length) throw new Error('UserAchievement not found');
    return this.formatUserAchievementResponse(result.rows[0]);
  }

async getUserAchievementById(id: string): Promise<UserAchievementResponse> {
    const result = await this.db.query('SELECT * FROM user_achievements WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('UserAchievement not found');
    
    return this.formatUserAchievementResponse(result.rows[0]);
  }

async getAllUser_achievements(): Promise<UserAchievementResponse[]> {
    const result = await this.db.query('SELECT * FROM user_achievements ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserAchievementResponse(row));
  }

async listUserAchievements(): Promise<UserAchievementResponse[]> {
    const result = await this.db.query('SELECT * FROM user_achievements ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserAchievementResponse(row));
  }

private formatUserAchievementResponse(row: any): UserAchievementResponse {
    return {
      id: row.id,
      user_id: row.user_id,
      achievement_id: row.achievement_id,
      earned_at: row.earned_at,
      progress: row.progress,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}