/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserContentProgreResponse, CreateUserContentProgreRequest, UpdateUserContentProgreRequest } from '../models/UserContentProgre';

export class UserContentProgreService {
  private db = Database.getInstance();

async createUserContentProgre(data: CreateUserContentProgreRequest): Promise<UserContentProgreResponse> {
    const { user_id, content_id, status, progress_percentage, time_spent, completion_score, started_at, completed_at, last_accessed, notes, bookmarked } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO user_content_progress (id, user_id, content_id, status, progress_percentage, time_spent, completion_score, started_at, completed_at, last_accessed, notes, bookmarked, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
      RETURNING *
    `, [id, user_id, content_id, status, progress_percentage, time_spent, completion_score, started_at, completed_at, last_accessed, notes, bookmarked]);
    
    return this.formatUserContentProgreResponse(result.rows[0]);
  }

async listUserContentProgres(): Promise<UserContentProgreResponse[]> {
    const result = await this.db.query('SELECT * FROM user_content_progress ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserContentProgreResponse(row));
  }

async getAllUser_content_progress(): Promise<UserContentProgreResponse[]> {
    const result = await this.db.query('SELECT * FROM user_content_progress ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserContentProgreResponse(row));
  }

async deleteUserContentProgre(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM user_content_progress WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('UserContentProgre not found');
  }

async getUserContentProgreById(id: string): Promise<UserContentProgreResponse> {
    const result = await this.db.query('SELECT * FROM user_content_progress WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('UserContentProgre not found');
    
    return this.formatUserContentProgreResponse(result.rows[0]);
  }

async updateUserContentProgre(id: string, data: UpdateUserContentProgreRequest): Promise<UserContentProgreResponse> {
    const { user_id, content_id, status, progress_percentage, time_spent, completion_score, started_at, completed_at, last_accessed, notes, bookmarked } = data;
    const result = await this.db.query(`
      UPDATE user_content_progress 
      SET user_id = $2, content_id = $3, status = $4, progress_percentage = $5, time_spent = $6, completion_score = $7, started_at = $8, completed_at = $9, last_accessed = $10, notes = $11, bookmarked = $12, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, user_id, content_id, status, progress_percentage, time_spent, completion_score, started_at, completed_at, last_accessed, notes, bookmarked]);
    
    if (!result.rows.length) throw new Error('UserContentProgre not found');
    return this.formatUserContentProgreResponse(result.rows[0]);
  }

private formatUserContentProgreResponse(row: any): UserContentProgreResponse {
    return {
      id: row.id,
      user_id: row.user_id,
      content_id: row.content_id,
      status: row.status,
      progress_percentage: row.progress_percentage,
      time_spent: row.time_spent,
      completion_score: row.completion_score,
      started_at: row.started_at,
      completed_at: row.completed_at,
      last_accessed: row.last_accessed,
      notes: row.notes,
      bookmarked: row.bookmarked,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}