/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserResponse, CreateUserRequest, UpdateUserRequest } from '../models/User';

export class UserService {
  private db = Database.getInstance();

async getAllUsers(): Promise<UserResponse[]> {
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserResponse(row));
  }

async getUserById(id: string): Promise<UserResponse> {
    const result = await this.db.query('SELECT * FROM users WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('User not found');
    
    return this.formatUserResponse(result.rows[0]);
  }

async updateUser(id: string, data: UpdateUserRequest): Promise<UserResponse> {
    const { username, email, password_hash, chess_elo, puzzle_rating, preferences } = data;
    const result = await this.db.query(`
      UPDATE users 
      SET username = $2, email = $3, password_hash = $4, chess_elo = $5, puzzle_rating = $6, preferences = $7, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, username, email, password_hash, chess_elo, puzzle_rating, preferences]);
    
    if (!result.rows.length) throw new Error('User not found');
    return this.formatUserResponse(result.rows[0]);
  }

async createUser(data: CreateUserRequest): Promise<UserResponse> {
    const { username, email, password_hash, chess_elo, puzzle_rating, preferences } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO users (id, username, email, password_hash, chess_elo, puzzle_rating, preferences, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
      RETURNING *
    `, [id, username, email, password_hash, chess_elo, puzzle_rating, preferences]);
    
    return this.formatUserResponse(result.rows[0]);
  }

async deleteUser(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM users WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('User not found');
  }

async listUsers(): Promise<UserResponse[]> {
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserResponse(row));
  }

private formatUserResponse(row: any): UserResponse {
    return {
      id: row.id,
      username: row.username,
      email: row.email,
      password_hash: row.password_hash,
      chess_elo: row.chess_elo,
      puzzle_rating: row.puzzle_rating,
      preferences: row.preferences,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}