/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserSessionResponse, CreateUserSessionRequest, UpdateUserSessionRequest } from '../models/UserSession';

export class UserSessionService {
  private db = Database.getInstance();

async listUserSessions(): Promise<UserSessionResponse[]> {
    const result = await this.db.query('SELECT * FROM user_sessions ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserSessionResponse(row));
  }

async deleteUserSession(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM user_sessions WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('UserSession not found');
  }

async createUserSession(data: CreateUserSessionRequest): Promise<UserSessionResponse> {
    const { user_id, refresh_token, expires_at } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO user_sessions (id, user_id, refresh_token, expires_at, created_at, updated_at)
      VALUES ($1, $2, $3, $4, NOW(), NOW())
      RETURNING *
    `, [id, user_id, refresh_token, expires_at]);
    
    return this.formatUserSessionResponse(result.rows[0]);
  }

async updateUserSession(id: string, data: UpdateUserSessionRequest): Promise<UserSessionResponse> {
    const { user_id, refresh_token, expires_at } = data;
    const result = await this.db.query(`
      UPDATE user_sessions 
      SET user_id = $2, refresh_token = $3, expires_at = $4, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, user_id, refresh_token, expires_at]);
    
    if (!result.rows.length) throw new Error('UserSession not found');
    return this.formatUserSessionResponse(result.rows[0]);
  }

async getAllUser_sessions(): Promise<UserSessionResponse[]> {
    const result = await this.db.query('SELECT * FROM user_sessions ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserSessionResponse(row));
  }

async getUserSessionById(id: string): Promise<UserSessionResponse> {
    const result = await this.db.query('SELECT * FROM user_sessions WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('UserSession not found');
    
    return this.formatUserSessionResponse(result.rows[0]);
  }

private formatUserSessionResponse(row: any): UserSessionResponse {
    return {
      id: row.id,
      user_id: row.user_id,
      refresh_token: row.refresh_token,
      expires_at: row.expires_at,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}