/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ChildPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/child_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { MobileChessboardLayout } from "../../components/chess/MobileChessboardLayout";

interface MobileProfilePageProps {
  // Add mobile-specific props as needed
}

export const MobileProfilePage: React.FC<MobileProfilePageProps> = () => {
  return (
    <div className="uitest-mobile-container-padded">
      <MobileChessboardLayout
        topPieces={<div className="uitest-mobile-pieces">Profile Top Pieces</div>}
        center={<div className="uitest-mobile-center">Profile Content</div>}
        bottomPieces={<div className="uitest-mobile-pieces">Profile Bottom Pieces</div>}
      />
    </div>
  );
};