/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useSettingsActions } from "../../hooks/settings/useSettingsActions";
import { SettingsMainPage } from "./SettingsMainPage";
import { PreferencesPageWrapper } from "../../components/settings/PreferencesPageWrapper";
import { ProfilePageWrapper } from "../../components/settings/ProfilePageWrapper";

interface SettingsPageProps {
  // Add props as needed
}

export const SettingsPage: React.FC<SettingsPageProps> = () => {
  const currentChildPage = useAppStore((state) => state.currentChildPage);
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("settings");
  usePageActions("settings");
  
  // Use parent actions hook for navigation methods
  useSettingsActions();
  
  // Default to main page
  let CurrentPageComponent = SettingsMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "preferences") {
    CurrentPageComponent = PreferencesPageWrapper;
  } else  if (currentChildPage === "profile") {
    CurrentPageComponent = ProfilePageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer />
    </>
  );
};