<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './DifficultySelector';
export * from './ErrorState';
export * from './GameControls';
export * from './GameResultModal';
export * from './GameStatusBar';
export * from './LoadingState';
export * from './PlayChessPageWrapper';
export * from './PlayMainPage';
export * from './PlayPuzzlesPageWrapper';
=======
// Auto-generated barrel export for play
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './DifficultySelector';
export * from './GameControls';
export * from './PlayChessPageWrapper';

// Default exports
export { default as PlayMainPage } from './PlayMainPage';
export { default as PlayPuzzlesPageWrapper } from './PlayPuzzlesPageWrapper';

// Mixed exports (default + named)
export * from './ErrorState';
export * from './GameResultModal';
export * from './GameStatusBar';
export * from './LoadingState';
>>>>>>> Stashed changes
