/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ChildPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/child_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { SettingsPage } from "../../pages/profile/SettingsPage";
import { MobileSettingsPage } from "../../pages/profile/MobileSettingsPage";

export const SettingsPageWrapper: React.FC = () => {
  // Mobile detection handled in wrapper (Phase 2 Architecture)
  const isMobile = useIsMobile();
  
  // Apply page context
  usePageInstructions("settings");
  usePageActions("settings");

  // Internal mobile/desktop switching
  return isMobile ? <MobileSettingsPage /> : <SettingsPage />;
};