/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { Express } from 'express';
import * as fs from 'fs';
import * as path from 'path';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Generated Backend API',
      description: 'API documentation generated by Backend Generator v2',
      version: '1.0.0',
    },
    servers: [
      {
        url: 'http://localhost:3001',
        description: 'Development server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
  },
  apis: ['./src/routes/*.ts'], // Path to the API files
};

// Try to load pre-generated swagger.json if available
let swaggerSpec;
try {
  const swaggerPath = path.join(process.cwd(), 'swagger.json');
  if (fs.existsSync(swaggerPath)) {
    swaggerSpec = JSON.parse(fs.readFileSync(swaggerPath, 'utf8'));
    console.log('📖 Loaded pre-generated swagger specification');
  } else {
    swaggerSpec = swaggerJsdoc(options);
    console.log('📖 Generated swagger specification from JSDoc');
  }
} catch (error) {
  console.warn('⚠️  Failed to load swagger spec, falling back to JSDoc:', error.message);
  swaggerSpec = swaggerJsdoc(options);
}

export const setupSwagger = (app: Express): void => {
  // Swagger UI setup
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: 'Generated Backend API Documentation',
    swaggerOptions: {
      persistAuthorization: true,
    },
  }));
  
  // Serve raw JSON spec
  app.get('/api-docs.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });
  
  console.log('📖 Swagger documentation available at /api-docs');
  console.log('📄 Raw OpenAPI spec available at /api-docs.json');
};

export { swaggerSpec };