/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

/**
 * Dynamic PAGE_ACTIONS Registry - Generated from pages.config.json
 * 
 * This registry automatically imports all generated page actions and provides
 * dynamic action discovery for the ActionSheetContainer.
 */
import type { ActionSheetAction } from '../../types/core/action-sheet.types'
import { mergeWithCommonActions } from './common-actions.constants'

// Dynamic imports for all generated page actions
import { pageActions as pageoneActions } from "./pages/pageone";
import { pageActions as pagetwoActions } from "./pages/pagetwo";
import { pageActions as testsectionActions } from "./pages/testsection";
import { pageActions as trendingActions } from "./pages/trending";
import { pageActions as genresActions } from "./pages/genres";
import { pageActions as discoverActions } from "./pages/discover";
import { pageActions as playlistsActions } from "./pages/playlists";
import { pageActions as downloadsActions } from "./pages/downloads";
import { pageActions as libraryActions } from "./pages/library";
import { pageActions as songsActions } from "./pages/songs";
import { pageActions as artistsActions } from "./pages/artists";
import { pageActions as searchActions } from "./pages/search";
import { pageActions as statsActions } from "./pages/stats";
import { pageActions as settingsActions } from "./pages/settings";
import { pageActions as profileActions } from "./pages/profile";

/**
 * Central registry of all page actions.
 * Automatically updated when new pages are generated.
 */
export const PAGE_ACTIONS: Record<string, ActionSheetAction[]> = {
  pageone: mergeWithCommonActions([
    ...pageoneActions.actions
  ], ['go-to-pagetwo']),
  pagetwo: mergeWithCommonActions([
    ...pagetwoActions.actions
  ], ['go-to-pageone']),
  testsection: mergeWithCommonActions([...testsectionActions.actions], []),
  trending: mergeWithCommonActions([
    ...trendingActions.actions
  ], ['go-to-genres']),
  genres: mergeWithCommonActions([
    ...genresActions.actions
  ], ['go-to-trending']),
  discover: mergeWithCommonActions([...discoverActions.actions], []),
  playlists: mergeWithCommonActions([
    ...playlistsActions.actions
  ], ['go-to-downloads']),
  downloads: mergeWithCommonActions([
    ...downloadsActions.actions
  ], ['go-to-playlists']),
  library: mergeWithCommonActions([...libraryActions.actions], []),
  songs: mergeWithCommonActions([
    ...songsActions.actions
  ], ['go-to-artists']),
  artists: mergeWithCommonActions([
    ...artistsActions.actions
  ], ['go-to-songs']),
  search: mergeWithCommonActions([...searchActions.actions], []),
  stats: mergeWithCommonActions([
    ...statsActions.actions
  ], ['go-to-settings']),
  settings: mergeWithCommonActions([
    ...settingsActions.actions
  ], ['go-to-stats']),
  profile: mergeWithCommonActions([...profileActions.actions], []),
}

/**
 * Helper function to get actions for a specific page.
 * Returns empty array if page not found.
 */
export function getPageActions(pageId: string): ActionSheetAction[] {
  return PAGE_ACTIONS[pageId] || [];
}

/**
 * Helper function to check if page has actions.
 */
export function hasPageActions(pageId: string): boolean {
  const actions = PAGE_ACTIONS[pageId];
  return actions && actions.length > 0;
}

/**
 * Get all page IDs that have actions defined.
 */
export function getPageIdsWithActions(): string[] {
  return Object.keys(PAGE_ACTIONS);
}