<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './AnalysisPageWrapper';
export * from './CapturedPieces';
export * from './CheckmateModal';
export * from './ChessboardLayout';
export * from './ChessGrid';
export * from './ChessOverlay';
export * from './DraggedPiece';
export * from './EndgamesPageWrapper';
export * from './GamesPageWrapper';
export * from './HistoricGamesPageWrapper';
export * from './MobileAnalysisPageWrapper';
export * from './MobileChessBoard';
export * from './MobileChessboardLayout';
export * from './MobileChessSquare';
export * from './MobileEndgamesPageWrapper';
export * from './MobileGamesPageWrapper';
export * from './MobileHistoricGamesPageWrapper';
export * from './MobileOpeningsPageWrapper';
export * from './MobilePuzzlesPageWrapper';
export * from './OpeningsPageWrapper';
export * from './PieceWrapper';
export * from './PromotionModal';
export * from './PuzzlesPageWrapper';
=======
// Auto-generated barrel export for chess
// Generated by AdvancedBarrelGenerator

// Default exports
export { default as CapturedPieces } from './CapturedPieces';
export { default as CheckmateModal } from './CheckmateModal';
export { default as ChessboardLayout } from './ChessboardLayout';
export { default as MobileChessBoard } from './MobileChessBoard';
export { default as MobileChessboardLayout } from './MobileChessboardLayout';
export { default as PromotionModal } from './PromotionModal';

// Mixed exports (default + named)
export * from './ChessGrid';
export * from './ChessOverlay';
export * from './DraggedPiece';
export * from './MobileChessSquare';
export * from './PieceWrapper';
>>>>>>> Stashed changes
