<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './AbstractEffects';
export * from './CasinoEffects';
export * from './GamingEffects';
export * from './MinimalEffects';
export * from './ParticleEffects';
=======
// Auto-generated barrel export for effects
// Generated by AdvancedBarrelGenerator

// Default exports
export { default as AbstractEffects } from './AbstractEffects';
export { default as CasinoEffects } from './CasinoEffects';
export { default as GamingEffects } from './GamingEffects';
export { default as MinimalEffects } from './MinimalEffects';
export { default as ParticleEffects } from './ParticleEffects';
>>>>>>> Stashed changes
