<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

=======
// Auto-generated barrel export for splash
// Generated by AdvancedBarrelGenerator

// Named exports only
>>>>>>> Stashed changes
export * from './AnimatedSplashPage';
export * from './BrandedSplashPage';
export * from './FunctionalSplashPage';
export * from './LoadingProgressPage';
export * from './LuxurysplashPage';
export * from './MinimalSplashPage';
<<<<<<< Updated upstream
export * from './SplashPage';
=======
export * from './SplashPage';
>>>>>>> Stashed changes
