/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export * from './auth.service';

export { ChessGameService, FenService, PlayGameService, MobileChessGameService, getStockfishSingletonStats, getStockfishService, TestBoardGameService, ComputerOpponentService, StockfishService, destroyStockfishSingleton } from './chess';
export type { GameState, GameStatus, StockfishHandlers, PieceColor, MoveResult } from './chess';
export { StockfishEngineClient } from './clients';
export { instructionsService, InstructionsService, pageInstructions } from './instructions';
export type { PageInstructions } from './instructions';
export { assetCacheService, preloadingService, PreloadingService, AssetCacheService } from './preloading';
export type { LoadingPriority, LoadingProgress, LoadingResults } from './preloading';