<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './auth.service';

export { AchievementsService } from './achievements';
export { AiOpponentsService } from './ai-opponents';
export { AnalysisService } from './analysis';
export { AnalyticsService } from './analytics';
export { puzzleApiService } from './api';
export { FenService, ComputerOpponentService, PlayGameService, getStockfishSingletonStats, destroyStockfishSingleton, MobileChessGameService, StockfishService, TestBoardGameService, getStockfishService, ChessGameService } from './chess';
export type { StockfishHandlers, MoveResult, PieceColor, GameState, GameStatus } from './chess';
export { StockfishEngineClient } from './clients';
export { EndgamesService } from './endgames';
export { GameReviewsService } from './game-reviews';
export { GamesService } from './games';
export { HelpService } from './help';
export { HistoricGamesService } from './historic-games';
export { instructionsService, InstructionsService, dynamicInstructionsService } from './instructions';
export type { PageInstructions } from './instructions';
export { LearningService } from './learning';
export { LearningModulesService } from './learning-modules';
export { OpeningsService } from './openings';
export { preloadingService, assetCacheService, PreloadingService, AssetCacheService } from './preloading';
export type { LoadingProgress, LoadingPriority, LoadingResults } from './preloading';
export { ProfilesService } from './profiles';
export { ProgressService } from './progress';
export { PuzzleAttemptsService } from './puzzle-attempts';
export { PuzzleSourcesService } from './puzzle-sources';
export { PuzzlesService } from './puzzles';
export { SessionsService } from './sessions';
export { StatsService } from './stats';
export { StudyPlansService } from './study-plans';
export { SubscriptionsService } from './subscriptions';
export { TutorialStepsService } from './tutorial-steps';
export { TutorialsService } from './tutorials';
export { UsersService } from './users';
=======
// Auto-generated barrel export for services
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './auth.service';

// Subdirectory exports
export * from './api';
export * from './audio';
export * from './chess';
export * from './clients';
export * from './core';
export * from './instructions';
export * from './preloading';
export * from './workers';
>>>>>>> Stashed changes
