/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { ForgotPasswordPageContent } from "../../pages/user/ForgotPasswordPageContent";
import AuthLayout from "./AuthLayout";
import type { AuthPage } from "../../components/auth/AuthRouter";

interface ForgotPasswordPageWrapperProps {
  onNavigate?: (page: AuthPage) => void;
}

export const ForgotPasswordPageWrapper: React.FC<ForgotPasswordPageWrapperProps> = ({ onNavigate }) => {
  usePageInstructions("forgotPassword");
  
  return (
    <AuthLayout>
      <ForgotPasswordPageContent onNavigate={onNavigate} />
    </AuthLayout>
  );
};