/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// Re-export all hooks and types for backward compatibility
export { 
  useSelectedTab, 
  useNavigation, 
  useSplashModal, 
  useCoinsModal,
  useSettings,
  useUIStore 
} from './uiStore'
export { useTheme, useAudio, useVisual } from './settingsStore'

// Legacy useAppStore function for backward compatibility
import { useUIStore } from './uiStore'
import { useSettingsStore } from './settingsStore'

export const useAppStore = <T = ReturnType<typeof useUIStore> & ReturnType<typeof useSettingsStore>>(
  selector?: (state: ReturnType<typeof useUIStore> & ReturnType<typeof useSettingsStore>) => T
): T => {
  const uiState = useUIStore()
  const settingsState = useSettingsStore()
  
  const combinedState = {
    // UI state
    selectedTab: uiState.selectedTab,
    currentChildPage: uiState.currentChildPage,
    setSelectedTab: uiState.setSelectedTab,
    setCurrentChildPage: uiState.setCurrentChildPage,
    splashModalOpen: uiState.splashModalOpen,
    splashModalPage: uiState.splashModalPage,
    openSplashModal: uiState.openSplashModal,
    closeSplashModal: uiState.closeSplashModal,
    lastVisited: uiState.lastVisited,
    
    // Settings state
    currentTheme: settingsState.currentTheme,
    audioEnabled: settingsState.audioEnabled,
    audioVolume: settingsState.audioVolume,
    backgroundEffectVariant: settingsState.backgroundEffectVariant,
    setBackgroundEffectVariant: settingsState.setBackgroundEffectVariant,
  }
  
  if (selector) {
    return selector(combinedState)
  }
  
  return combinedState as T
}