/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export type { GlobalUIAudioService, UIInteractionConfig, UIExclusionConfig, GlobalUIAudioConfig, ElementDetectionResult, GlobalClickHandler, GlobalUIAudioConfigUpdate, UISoundType, UIElementSelector, UIInteractionType } from './audio';
export type { AuthState, ProtectedRouteProps, RegisterResponse, UseLoginReturn, FormValidationError, AuthStorage, LoginResponse, RegisterData, LoginRequest, RegisterRequest, VerifyTokenRequest, ChangePasswordRequest, AuthActions, MeResponse, TokenVerificationResponse, AuthError, TokenInfo, AuthResponse, UserProgress, ResetPasswordRequest, AuthGuardProps, AuthErrorType, User, ForgotPasswordRequest, AuthFormState, LoginCredentials, AuthConfig, AuthApiClient, UseForgotPasswordReturn, UseRegisterReturn, UpdateProfileRequest, UseAuthReturn, AuthContextValue } from './auth';
export type { ActionSheetAction, BackgroundEffectVariant, IBackgroundEffectsService, BackgroundEffectProps, ActionSheetProps, BackgroundEffectConfig, ActionSheetContainerProps } from './core';
export type { UserPreferences, UserStats, PrivacySettings, UserManagementResponse, GameplaySettings, UserRole, PaginatedUsersResponse, UserProfile, UserManagementError, NotificationSettings, UserSession, ChangePasswordData, UpdateProfileData } from './user-management';