<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './computer-chess.utils';
export * from './mobile-chess.utils';
export * from './mobileBoardUtils';
export * from './play-game.utils';
=======
// Auto-generated barrel export for chess
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './computer-chess.utils';
export * from './mobile-chess.utils';
export * from './mobileBoardUtils';
export * from './play-game.utils';
>>>>>>> Stashed changes
