/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for Auth

export interface Auth {
  id: string;
  username: string;
  email: string;
  created_at: string;
  updated_at: string;
}

export interface AuthCreate {
  // Properties needed for creating new Auth
  id: string;
  username: string;
  email: string;
  created_at: string;
  updated_at: string;
}

export interface AuthUpdate {
  // Properties that can be updated
  id: string;
  username: string;
  email: string;
  created_at: string;
  updated_at: string;
}

export interface AuthFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
