/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import { useState, useCallback } from 'react'

/**
 * Hook for action sheet state management only
 * Following SRP - ONLY manages open/close state, no business logic
 * Matches existing pattern from useMenuDropdown.ts
 */
export function useActionSheet() {
  const [isOpen, setIsOpen] = useState(false)

  const openSheet = useCallback(() => {
    setIsOpen(true)
  }, [])

  const closeSheet = useCallback(() => {
    setIsOpen(false)
  }, [])

  const toggleSheet = useCallback(() => {
    setIsOpen(prev => !prev)
  }, [isOpen])

  return {
    isOpen,
    openSheet,
    closeSheet,
    toggleSheet
  }
}