/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import { useEffect } from 'react'
import { useAppStore } from '../../stores/appStore'

/**
 * Hook to automatically set the current child page for action sheet context
 * This mirrors the pattern used by usePageInstructions but uses the app store
 */
export const usePageActions = (pageId: string) => {
  const setCurrentChildPage = useAppStore((state: any) => state.setCurrentChildPage)
  
  useEffect(() => {
    // Set the current child page in the store
    setCurrentChildPage(pageId)
    
    // Cleanup: clear child page when component unmounts
    return () => {
      setCurrentChildPage(null)
    }
  }, [pageId, setCurrentChildPage])
}