/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { LoginRequest, RegisterRequest, UserInfo, AuthResponse, CreateAuthRequest, UpdateAuthRequest } from '../models/Auth';

export class AuthService {
  private db = Database.getInstance();

async deleteAuth(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM users WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('Auth not found');
  }

async createAuth(data: CreateAuthRequest): Promise<AuthResponse> {
    const { username, email } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO users (id, username, email, created_at, updated_at)
      VALUES ($1, $2, $3, NOW(), NOW())
      RETURNING *
    `, [id, username, email]);
    
    return this.formatAuthResponse(result.rows[0]);
  }

  async logout(...args: any[]): Promise<any> {
    // Generic implementation for logout
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatAuthResponse(row));
  }

async getAuthById(id: string): Promise<AuthResponse> {
    const result = await this.db.query('SELECT * FROM users WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('Auth not found');
    
    return this.formatAuthResponse(result.rows[0]);
  }

async getAllAuth(): Promise<AuthResponse[]> {
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatAuthResponse(row));
  }

async updateAuth(id: string, data: UpdateAuthRequest): Promise<AuthResponse> {
    const { username, email } = data;
    const result = await this.db.query(`
      UPDATE users 
      SET username = $2, email = $3, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, username, email]);
    
    if (!result.rows.length) throw new Error('Auth not found');
    return this.formatAuthResponse(result.rows[0]);
  }

async login(loginData: any): Promise<any> {
    const { email, password } = loginData;

    // Find user by email
    const result = await this.db.query(
      'SELECT * FROM users WHERE email = $1',
      [email]
    );

    if (!result.rows.length) {
      throw new Error('Invalid credentials');
    }

    const user = result.rows[0];

    // Verify password
    const bcrypt = require('bcrypt');
    const isValidPassword = await bcrypt.compare(password, user.password_hash);
    if (!isValidPassword) {
      throw new Error('Invalid credentials');
    }

    // Generate JWT token
    const jwt = require('jsonwebtoken');
    const token = jwt.sign(
      { 
        id: user.id, 
        email: user.email,
        username: user.username 
      },
      process.env.JWT_SECRET!,
      { expiresIn: '7d' }
    );

    return {
      user: this.formatAuthResponse(user),
      token
    };
  }

  async getCurrentUser(...args: any[]): Promise<any> {
    // Generic implementation for getCurrentUser
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatAuthResponse(row));
  }

async register(registerData: any): Promise<any> {
    const { username, email, password } = registerData;

    // Check if user already exists
    const existingUser = await this.db.query(
      'SELECT id FROM users WHERE email = $1 OR username = $2',
      [email, username]
    );

    if (existingUser.rows.length > 0) {
      throw new Error('User with this email or username already exists');
    }

    // Hash password
    const bcrypt = require('bcrypt');
    const passwordHash = await bcrypt.hash(password, 12);

    // Create user
    const userId = require('uuid').v4();
    const result = await this.db.query(`
      INSERT INTO users (id, username, email, password_hash, chess_elo, puzzle_rating, preferences, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
      RETURNING *
    `, [userId, username, email, passwordHash, 1000, 1000, '{}']);

    if (!result.rows.length) {
      throw new Error('Failed to create user');
    }

    return this.formatAuthResponse(result.rows[0]);
  }

private formatAuthResponse(row: any): AuthResponse {
    return {
      id: row.id,
      username: row.username,
      email: row.email,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}