/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

import { v4 as uuidv4 } from 'uuid';
import { Database } from '../utils/database';
import { UserResponse, CreateUserRequest, UpdateUserRequest } from '../models/User';

export class UserService {
  private db = Database.getInstance();

async createUser(data: CreateUserRequest): Promise<UserResponse> {
    const { username, email, chess_elo, puzzle_rating } = data;
    const id = uuidv4();
    const result = await this.db.query(`
      INSERT INTO users (id, username, email, chess_elo, puzzle_rating, created_at, updated_at)
      VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
      RETURNING *
    `, [id, username, email, chess_elo, puzzle_rating]);
    
    return this.formatUserResponse(result.rows[0]);
  }

async updateUserProfile(id: string, data: UpdateUserRequest): Promise<UserResponse> {
    const { username, email, chess_elo, puzzle_rating } = data;
    const result = await this.db.query(`
      UPDATE users 
      SET username = $2, email = $3, chess_elo = $4, puzzle_rating = $5, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, username, email, chess_elo, puzzle_rating]);
    
    if (!result.rows.length) throw new Error('User not found');
    return this.formatUserResponse(result.rows[0]);
  }

async getUserById(id: string): Promise<UserResponse> {
    const result = await this.db.query('SELECT * FROM users WHERE id = $1', [id]);
    if (!result.rows.length) throw new Error('User not found');
    
    return this.formatUserResponse(result.rows[0]);
  }

async updateUser(id: string, data: UpdateUserRequest): Promise<UserResponse> {
    const { username, email, chess_elo, puzzle_rating } = data;
    const result = await this.db.query(`
      UPDATE users 
      SET username = $2, email = $3, chess_elo = $4, puzzle_rating = $5, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [id, username, email, chess_elo, puzzle_rating]);
    
    if (!result.rows.length) throw new Error('User not found');
    return this.formatUserResponse(result.rows[0]);
  }

async deleteUser(id: string): Promise<void> {
    const result = await this.db.query('DELETE FROM users WHERE id = $1', [id]);
    if (result.rowCount === 0) throw new Error('User not found');
  }

async getAllUsers(): Promise<UserResponse[]> {
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserResponse(row));
  }

  async getUserProfile(...args: any[]): Promise<any> {
    // Generic implementation for getUserProfile
    const result = await this.db.query('SELECT * FROM users ORDER BY created_at DESC LIMIT 50');
    return result.rows.map(row => this.formatUserResponse(row));
  }

private formatUserResponse(row: any): UserResponse {
    return {
      id: row.id,
      username: row.username,
      email: row.email,
      chess_elo: row.chess_elo,
      puzzle_rating: row.puzzle_rating,
      created_at: row.created_at,
      updated_at: row.updated_at,
    };
  }
}