/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useSearchActions } from "../../hooks/search/useSearchActions";
import { SearchMainPage } from "./SearchMainPage";

import { MobileSearchMainPage } from "./MobileSearchMainPage";
import { ArtistsPageWrapper } from "../../components/search/ArtistsPageWrapper";
import { SongsPageWrapper } from "../../components/search/SongsPageWrapper";

interface SearchPageProps {
  // Add props as needed
}

export const SearchPage: React.FC<SearchPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  const isMobile = useIsMobile();
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("search");
  usePageActions("search");
  
  // Use parent actions hook for navigation methods
  useSearchActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = isMobile ? MobileSearchMainPage : SearchMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "artists") {
    CurrentPageComponent = ArtistsPageWrapper;
  } else  if (currentChildPage === "songs") {
    CurrentPageComponent = SongsPageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="search"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};