import { useEffect } from "react";
import { AppLayout } from "./components/layout";
import { useGlobalUIAudio } from "./hooks/audio/useGlobalUIAudio";

import { DragProvider, useDrag } from "./providers/DragProvider";
import { InstructionsProvider } from "./contexts/InstructionsContext";
import { DraggedPiece } from "./components/chess/DraggedPiece";
import { SplashModal } from "./components/splash/SplashModal";
import { useSelectedTab, useAppStore } from "./stores/appStore";
import { useChessAudio } from "./services/audio/audioService";
import { useAuthStatus } from "./hooks";
import { AuthRouter } from "./components/auth/AuthRouter";

import { ChessPage } from "./pages/chess/ChessPage";
import { UserPage } from "./pages/user/UserPage";
import { LearningPage } from "./pages/learning/LearningPage";
import { ProgressPage } from "./pages/progress/ProgressPage";
import { SupportPage } from "./pages/support/SupportPage";
import { OtherPage } from "./pages/other/OtherPage";

/*
 * This App.tsx was generated by the frontend generator.
 * The tabs and routing are automatically configured based on your domain structure.
 * 
 * Generated tabs: chess, user, learning, progress, support, other
 */

function AppContent() {
  const selectedTab = useSelectedTab();
  const setSelectedTab = useAppStore((state) => state.setSelectedTab);
  const coinBalance = useAppStore((state) => state.coinBalance);
  const { draggedPiece, cursorPosition, draggedPieceSize } = useDrag();
  const { preloadSounds, playGameStart } = useChessAudio();
  const { isAuthenticated, isLoading: authLoading } = useAuthStatus();

  // Initialize Global UI Audio System
  useGlobalUIAudio({
    autoInitialize: true,
    initialConfig: {
      enabled: true,
      autoDetection: true,
      excludeSelectors: [
        '[data-no-sound]',
        '.no-sound',
        '.chess-piece',
        '.chess-square',
        '.chess-board',
        '[disabled]',
        '.disabled',
        '[data-headlessui-state]',
        '[data-action-item]',
        '.action-sheet-item'
      ]
    }
  });

  // Initialize audio system on first user interaction
  useEffect(() => {
    const handleFirstInteraction = () => {
      preloadSounds();
      playGameStart();

      document.removeEventListener("click", handleFirstInteraction);
      document.removeEventListener("keydown", handleFirstInteraction);
    };

    document.addEventListener("click", handleFirstInteraction, { once: true });
    document.addEventListener("keydown", handleFirstInteraction, { once: true });

    return () => {
      document.removeEventListener("click", handleFirstInteraction);
      document.removeEventListener("keydown", handleFirstInteraction);
    };
  }, []);

  // Show auth pages if not authenticated
  if (!authLoading && !isAuthenticated) {
    return <AuthRouter />;
  }

  return (
    <AppLayout
      currentTab={selectedTab}
      onTabChange={setSelectedTab}
      coinBalance={coinBalance}
    >
      {/* Generated page routing */}
      {selectedTab === "chess" && <ChessPage />}
      {selectedTab === "user" && <UserPage />}
      {selectedTab === "learning" && <LearningPage />}
      {selectedTab === "progress" && <ProgressPage />}
      {selectedTab === "support" && <SupportPage />}
      {selectedTab === "other" && <OtherPage />}

      {/* Global drag overlay */}
      {draggedPiece && (
        <DraggedPiece
          piece={draggedPiece}
          position={cursorPosition}
          size={draggedPieceSize}
        />
      )}
    </AppLayout>
  );
}

function App() {
  return (
    <InstructionsProvider>
      <DragProvider>
        <AppContent />
        <SplashModal />
      </DragProvider>
    </InstructionsProvider>
  );
}

export default App;
