/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ChildPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/child_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
import { useIsMobile } from "../../hooks/core/useIsMobile";
import { GenresPage } from "../../pages/discover/GenresPage";
import { MobileGenresPage } from "../../pages/discover/MobileGenresPage";

export const GenresPageWrapper: React.FC = () => {
  // Mobile detection handled in wrapper (Phase 2 Architecture)
  const isMobile = useIsMobile();
  
  // Apply page context
  usePageInstructions("genres");
  usePageActions("genres");

  // Internal mobile/desktop switching
  return isMobile ? <MobileGenresPage /> : <GenresPage />;
};