#!/usr/bin/env python3
"""
Migration script for converting projects from old generators to new template-based system.
Detects old generator patterns and converts them to new template-based structure.
"""

import sys
import os
import re
from pathlib import Path
from typing import List, Dict, Set, Optional
import argparse

# Add modules to path  
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from modules.config import PageConfig, GenerationContext, ProjectCapabilities
from modules.project_detector import ProjectCapabilityDetector
from modules.template_engine import TemplateEngine
from modules.file_writer import FileWriter
from modules.variable_generator import VariableGenerator
from modules.validation import ProjectValidator


class OldGeneratorPattern:
    """Represents patterns from old generators that need migration."""
    
    def __init__(self, pattern_type: str, file_pattern: str, content_patterns: List[str]):
        self.pattern_type = pattern_type  # 'dynamic', 'static', 'wrapper'
        self.file_pattern = file_pattern
        self.content_patterns = content_patterns


class MigrationDetector:
    """Detects old generator patterns in project files."""
    
    def __init__(self, frontend_root: Path):
        self.frontend_root = frontend_root
        self.src_dir = frontend_root / "src"
        
        # Define patterns from old generators
        self.old_patterns = [
            # Dynamic page generator patterns
            OldGeneratorPattern(
                "dynamic",
                "**/*Page.tsx",
                [
                    r"// Generated by.*dynamic.*generator",
                    r"// This file was auto-generated",
                    r"DynamicPageWrapper",
                    r"export.*DynamicPage"
                ]
            ),
            
            # Old page generator patterns
            OldGeneratorPattern(
                "static", 
                "**/*Page.tsx",
                [
                    r"// Generated by.*page.*generator",
                    r"StaticPageWrapper",
                    r"// Auto-generated page component"
                ]
            ),
            
            # Old wrapper patterns (parent wrappers that should be removed)
            OldGeneratorPattern(
                "wrapper",
                "**/components/**/*Wrapper.tsx",
                [
                    r"// Parent wrapper component",
                    r"// Generated wrapper",
                    r"MobileWrapper.*Parent"
                ]
            )
        ]
    
    def detect_old_generator_files(self) -> Dict[str, List[Path]]:
        """Detect files generated by old generators."""
        detected_files = {
            "dynamic": [],
            "static": [], 
            "wrapper": [],
            "unknown": []
        }
        
        print("🔍 Scanning for old generator patterns...")
        
        if not self.src_dir.exists():
            print(f"  ⚠️  Source directory not found: {self.src_dir}")
            return detected_files
        
        # Scan all relevant files
        for pattern in self.old_patterns:
            for file_path in self.src_dir.glob(pattern.file_pattern):
                if file_path.is_file():
                    try:
                        content = file_path.read_text(encoding='utf-8')
                        
                        # Check if file matches any old generator pattern
                        for content_pattern in pattern.content_patterns:
                            if re.search(content_pattern, content, re.IGNORECASE):
                                detected_files[pattern.pattern_type].append(file_path)
                                print(f"  📄 Found {pattern.pattern_type}: {file_path.relative_to(self.frontend_root)}")
                                break
                                
                    except Exception as e:
                        print(f"  ⚠️  Error reading {file_path}: {e}")
        
        # Report totals
        total_found = sum(len(files) for files in detected_files.values())
        print(f"  📊 Total old generator files found: {total_found}")
        
        return detected_files
    
    def analyze_migration_complexity(self, detected_files: Dict[str, List[Path]]) -> Dict[str, any]:
        """Analyze the complexity of migration required."""
        analysis = {
            "total_files": sum(len(files) for files in detected_files.values()),
            "by_type": {},
            "parent_pages": set(),
            "child_pages": set(),
            "wrapper_cleanup": [],
            "complexity_score": 0
        }
        
        print("🔬 Analyzing migration complexity...")
        
        for pattern_type, files in detected_files.items():
            analysis["by_type"][pattern_type] = len(files)
            
            for file_path in files:
                rel_path = file_path.relative_to(self.src_dir)
                
                # Determine if it's a parent or child page
                if "pages" in rel_path.parts:
                    page_parts = list(rel_path.parts)
                    if "pages" in page_parts:
                        pages_index = page_parts.index("pages")
                        if len(page_parts) > pages_index + 1:
                            parent_name = page_parts[pages_index + 1]
                            
                            # If it's the main parent page (e.g., SettingsPage.tsx in settings/)
                            if file_path.stem == f"{parent_name.capitalize()}Page":
                                analysis["parent_pages"].add(parent_name)
                            else:
                                # It's likely a child page
                                analysis["child_pages"].add((parent_name, file_path.stem))
                
                # Check for parent wrappers that need removal
                if pattern_type == "wrapper" and "components" in rel_path.parts:
                    analysis["wrapper_cleanup"].append(file_path)
        
        # Calculate complexity score
        analysis["complexity_score"] = (
            len(analysis["parent_pages"]) * 2 +  # Parent pages are more complex
            len(analysis["child_pages"]) * 1 +   # Child pages are simpler
            len(analysis["wrapper_cleanup"]) * 3  # Wrapper cleanup is complex
        )
        
        print(f"  📊 Migration Analysis:")
        print(f"    Parents to migrate: {len(analysis['parent_pages'])}")
        print(f"    Children to migrate: {len(analysis['child_pages'])}")
        print(f"    Wrappers to cleanup: {len(analysis['wrapper_cleanup'])}")
        print(f"    Complexity Score: {analysis['complexity_score']}")
        
        return analysis


class ProjectMigrator:
    """Handles migration from old generators to new template-based system."""
    
    def __init__(self, frontend_root: Path, templates_dir: Path, dry_run: bool = True):
        self.frontend_root = frontend_root
        self.templates_dir = templates_dir
        self.dry_run = dry_run
        
        # Initialize components
        self.detector = MigrationDetector(frontend_root)
        self.project_detector = ProjectCapabilityDetector(frontend_root)
        self.template_engine = TemplateEngine(templates_dir)
        self.file_writer = FileWriter()
        self.variable_generator = VariableGenerator()
        self.validator = ProjectValidator(frontend_root, templates_dir)
    
    def run_migration(self) -> Dict[str, any]:
        """Run complete migration process."""
        print("🚀 Starting Migration Process")
        print("=" * 60)
        
        migration_report = {
            "detected_files": {},
            "analysis": {},
            "migration_plan": {},
            "execution_results": {},
            "validation_results": {}
        }
        
        # Step 1: Detect old generator files
        migration_report["detected_files"] = self.detector.detect_old_generator_files()
        
        if not any(migration_report["detected_files"].values()):
            print("✅ No old generator files detected. Migration not needed.")
            return migration_report
        
        # Step 2: Analyze migration complexity
        migration_report["analysis"] = self.detector.analyze_migration_complexity(
            migration_report["detected_files"]
        )
        
        # Step 3: Create migration plan
        migration_report["migration_plan"] = self._create_migration_plan(
            migration_report["analysis"]
        )
        
        # Step 4: Execute migration (if not dry run)
        if not self.dry_run:
            migration_report["execution_results"] = self._execute_migration(
                migration_report["migration_plan"]
            )
        else:
            print("🔍 DRY RUN MODE - No changes will be made")
            self._preview_migration(migration_report["migration_plan"])
        
        # Step 5: Validate results
        migration_report["validation_results"] = self._validate_migration()
        
        return migration_report
    
    def _create_migration_plan(self, analysis: Dict[str, any]) -> Dict[str, any]:
        """Create detailed migration plan."""
        print("\n📋 Creating Migration Plan...")
        
        plan = {
            "backup_originals": [],
            "remove_parent_wrappers": [],
            "convert_to_templates": [],
            "update_routing": [],
            "regenerate_dependencies": False
        }
        
        # Plan to backup all files being modified
        all_files = []
        for files in self.detector.detect_old_generator_files().values():
            all_files.extend(files)
        plan["backup_originals"] = all_files
        
        # Plan parent wrapper removal
        plan["remove_parent_wrappers"] = analysis["wrapper_cleanup"]
        
        # Plan template conversion for each page
        for parent in analysis["parent_pages"]:
            plan["convert_to_templates"].append({
                "type": "parent",
                "name": parent,
                "action": "convert_to_template_based"
            })
        
        for parent, child in analysis["child_pages"]:
            plan["convert_to_templates"].append({
                "type": "child",
                "name": child.replace("Page", ""),
                "parent": parent,
                "action": "convert_to_template_based"
            })
        
        # Plan routing updates
        plan["update_routing"] = list(analysis["parent_pages"])
        
        # Plan dependency regeneration if needed
        plan["regenerate_dependencies"] = len(analysis["parent_pages"]) > 0
        
        print(f"  📝 Migration Plan Created:")
        print(f"    Files to backup: {len(plan['backup_originals'])}")
        print(f"    Parent wrappers to remove: {len(plan['remove_parent_wrappers'])}")
        print(f"    Pages to convert: {len(plan['convert_to_templates'])}")
        print(f"    Routing updates needed: {len(plan['update_routing'])}")
        
        return plan
    
    def _preview_migration(self, plan: Dict[str, any]):
        """Preview what migration would do without making changes."""
        print("\n🔍 Migration Preview (Dry Run):")
        print("=" * 40)
        
        print("\n1. Backup Original Files:")
        for file_path in plan["backup_originals"]:
            rel_path = file_path.relative_to(self.frontend_root)
            print(f"   📋 Would backup: {rel_path}")
        
        print("\n2. Remove Parent Wrappers:")
        for wrapper_path in plan["remove_parent_wrappers"]:
            rel_path = wrapper_path.relative_to(self.frontend_root)
            print(f"   🗑️  Would remove: {rel_path}")
        
        print("\n3. Convert to Template-Based:")
        for conversion in plan["convert_to_templates"]:
            if conversion["type"] == "parent":
                print(f"   🔄 Would convert parent: {conversion['name']}")
            else:
                print(f"   🔄 Would convert child: {conversion['name']} (parent: {conversion['parent']})")
        
        print("\n4. Update Routing:")
        for parent in plan["update_routing"]:
            print(f"   🔗 Would update routing for: {parent}")
        
        if plan["regenerate_dependencies"]:
            print("\n5. Regenerate Dependencies:")
            print("   🔧 Would regenerate index files and dependencies")
    
    def _execute_migration(self, plan: Dict[str, any]) -> Dict[str, any]:
        """Execute the migration plan."""
        print("\n⚡ Executing Migration...")
        
        results = {
            "backups_created": [],
            "wrappers_removed": [], 
            "pages_converted": [],
            "routing_updated": [],
            "errors": []
        }
        
        try:
            # Step 1: Create backups
            print("  📋 Creating backups...")
            for file_path in plan["backup_originals"]:
                backup_path = file_path.with_suffix(f"{file_path.suffix}.backup")
                try:
                    backup_path.write_text(file_path.read_text())
                    results["backups_created"].append(backup_path)
                except Exception as e:
                    results["errors"].append(f"Backup failed for {file_path}: {e}")
            
            # Step 2: Remove parent wrappers
            print("  🗑️  Removing parent wrappers...")
            for wrapper_path in plan["remove_parent_wrappers"]:
                try:
                    wrapper_path.unlink()
                    results["wrappers_removed"].append(wrapper_path)
                except Exception as e:
                    results["errors"].append(f"Wrapper removal failed for {wrapper_path}: {e}")
            
            # Step 3: Convert pages to template-based
            print("  🔄 Converting to template-based...")
            capabilities = self.project_detector.detect_capabilities()
            
            for conversion in plan["convert_to_templates"]:
                try:
                    if conversion["type"] == "parent":
                        self._convert_parent_page(conversion["name"], capabilities)
                    else:
                        self._convert_child_page(
                            conversion["name"], 
                            conversion["parent"], 
                            capabilities
                        )
                    results["pages_converted"].append(conversion)
                except Exception as e:
                    results["errors"].append(f"Page conversion failed for {conversion}: {e}")
            
            # Step 4: Update routing
            print("  🔗 Updating routing...")
            # TODO: Implement routing updates
            
            # Step 5: Regenerate dependencies
            if plan["regenerate_dependencies"]:
                print("  🔧 Regenerating dependencies...")
                # TODO: Implement dependency regeneration
            
        except Exception as e:
            results["errors"].append(f"Migration execution failed: {e}")
        
        return results
    
    def _convert_parent_page(self, parent_name: str, capabilities: ProjectCapabilities):
        """Convert a parent page to template-based generation."""
        # This would use the existing parent generator logic
        # For now, just placeholder
        pass
    
    def _convert_child_page(self, child_name: str, parent_name: str, capabilities: ProjectCapabilities):
        """Convert a child page to template-based generation."""
        # This would use the existing child generator logic
        # For now, just placeholder
        pass
    
    def _validate_migration(self) -> Dict[str, any]:
        """Validate migration results."""
        print("\n✅ Validating Migration Results...")
        
        # Run comprehensive validation
        report = self.validator.run_comprehensive_validation()
        
        validation_results = {
            "overall_passed": report.passed,
            "total_checks": report.summary["total"],
            "passed_checks": report.summary["passed"],
            "failed_checks": report.summary["failed"],
            "critical_issues": len(self.validator.get_validation_issues(report, "error")),
            "warnings": len(self.validator.get_validation_issues(report, "warning"))
        }
        
        print(f"  📊 Validation Summary:")
        print(f"    Overall Status: {'✅ PASSED' if validation_results['overall_passed'] else '❌ FAILED'}")
        print(f"    Checks Passed: {validation_results['passed_checks']}/{validation_results['total_checks']}")
        print(f"    Critical Issues: {validation_results['critical_issues']}")
        print(f"    Warnings: {validation_results['warnings']}")
        
        return validation_results


def main():
    """Main CLI interface for migration tool."""
    parser = argparse.ArgumentParser(
        description="Migrate projects from old generators to template-based system",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s /path/to/frontend --dry-run
  %(prog)s /path/to/frontend --execute
  %(prog)s . --analyze-only
        """
    )
    
    parser.add_argument(
        'frontend_root',
        help='Path to frontend root directory'
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        default=True,
        help='Preview migration without making changes (default)'
    )
    
    parser.add_argument(
        '--execute',
        action='store_true',
        help='Actually execute the migration'
    )
    
    parser.add_argument(
        '--analyze-only',
        action='store_true',
        help='Only analyze and detect old patterns, do not create migration plan'
    )
    
    parser.add_argument(
        '--templates-dir',
        help='Path to templates directory (defaults to ./templates)'
    )
    
    args = parser.parse_args()
    
    # Determine dry run mode
    dry_run = not args.execute
    
    # Setup paths
    frontend_root = Path(args.frontend_root).resolve()
    if not frontend_root.exists():
        print(f"❌ Frontend root directory not found: {frontend_root}")
        sys.exit(1)
    
    templates_dir = Path(args.templates_dir) if args.templates_dir else Path(__file__).parent.parent / "templates"
    if not templates_dir.exists():
        print(f"❌ Templates directory not found: {templates_dir}")
        sys.exit(1)
    
    try:
        # Initialize migrator
        migrator = ProjectMigrator(frontend_root, templates_dir, dry_run)
        
        if args.analyze_only:
            # Just analyze and detect
            detected_files = migrator.detector.detect_old_generator_files()
            analysis = migrator.detector.analyze_migration_complexity(detected_files)
            
            print("\n📊 Analysis Complete:")
            if analysis["total_files"] == 0:
                print("✅ No migration needed - no old generator files detected")
            else:
                print(f"⚠️  {analysis['total_files']} files need migration")
                print(f"   Complexity Score: {analysis['complexity_score']}")
        else:
            # Run full migration
            migration_report = migrator.run_migration()
            
            # Print final summary
            print("\n" + "=" * 60)
            print("🏁 MIGRATION COMPLETE")
            print("=" * 60)
            
            total_files = sum(len(files) for files in migration_report["detected_files"].values())
            if total_files == 0:
                print("✅ No migration was needed")
            else:
                print(f"📊 Migration Summary:")
                print(f"   Files Processed: {total_files}")
                
                if "execution_results" in migration_report and migration_report["execution_results"]:
                    results = migration_report["execution_results"]
                    print(f"   Pages Converted: {len(results.get('pages_converted', []))}")
                    print(f"   Errors: {len(results.get('errors', []))}")
                    
                    if results.get('errors'):
                        print(f"\n⚠️  Errors occurred:")
                        for error in results['errors']:
                            print(f"   - {error}")
                
                if migration_report.get("validation_results"):
                    validation = migration_report["validation_results"]
                    status = "✅ PASSED" if validation["overall_passed"] else "❌ FAILED"
                    print(f"   Validation: {status}")
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Migration cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Migration failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()