/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

interface HeaderProps {
  onOpenSettings: () => void
  isSettingsOpen: boolean
}

export default function Header({ }: HeaderProps) {
  return (
    <div className="w-full h-16">
      <div className="container mx-auto px-6 h-full">
        <div className="flex items-center justify-between h-full">
          <div className="flex items-center gap-3">
            {/* Title and icon moved to TitleBar */}
          </div>
          
          <div className="flex items-center gap-4">
            {/* Header actions will be added here by specific apps */}
          </div>
        </div>
      </div>
    </div>
  )
}