/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export * from './auth.utils';
export * from './chess.utils';
export * from './coordinate.utils';
export * from './grid-generator.utils';

export { identifyReactComponent, getElementPath, getDeviceInfo, detectMobile, EventDeduplicator, getElementInfo } from './audio';
export type { DeviceInfo } from './audio';
export { screenCoordsToChessSquare, isLandscapeOrientation, formatEvaluation, exceedsDragThreshold, getSafeAreaInsets, formatGameTime, triggerHapticFeedback, calculateMobileBoardSize, chessSquareToScreenCoords, getMobileSquareColor, createUciMove, getTouchTargetSize, generateMobileBoardSquares, formatThinkingTime, detectTouchGesture, isValidTouchTarget, parseEngineMove, calculateThinkingTime, validateMoveString, addNaturalVariation, debounceTouchEvent, validateMoveFormat, calculateTouchDistance, normalizeTouchEvent, supportsHapticFeedback } from './chess';
export type { ParsedMove } from './chess';