/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export * from './puzzle.types';

export { AUDIO_FEEDBACK_PATTERNS, DEFAULT_AUDIO_TIMING, CHESS_BOARD_AUDIO_PROFILES, DEFAULT_CHESS_BOARD_AUDIO_CONFIG } from './audio';
export type { GlobalClickHandler, GlobalUIAudioConfig, ChessBoardAudioConfig, UISoundType, GlobalUIAudioService, UIExclusionConfig, GlobalUIAudioConfigUpdate, AudioFeedbackContext, ChessBoardAudioEvents, AudioFeedbackTiming, UIElementSelector, MoveAudioContext, AudioFeedbackDecision, ComponentAudioConfig, ChessBoardInteractionType, ElementDetectionResult, UIInteractionType, UIInteractionConfig, AudioFeedbackPattern, AudioFeedbackIntensity } from './audio';
export type { RegisterData, UseLoginReturn, LoginCredentials, AuthApiClient, UserProgress, RegisterRequest, LoginResponse, UpdateProfileRequest, ResetPasswordRequest, MeResponse, AuthResponse, VerifyTokenRequest, TokenInfo, AuthError, FormValidationError, TokenVerificationResponse, UseAuthReturn, UseForgotPasswordReturn, ForgotPasswordRequest, AuthFormState, AuthActions, AuthConfig, ProtectedRouteProps, User, AuthContextValue, UseRegisterReturn, RegisterResponse, AuthErrorType, LoginRequest, AuthStorage, AuthState, ChangePasswordRequest, AuthGuardProps } from './auth';
export { MOBILE_TOUCH_THRESHOLDS, MOBILE_BOARD_SIZE_PRESETS, DEFAULT_MOBILE_CHESS_CONFIG } from './chess';
export type { ComputerOpponentStatus, File, Rank, ChessPositionObject, MobileChessMoveResult, MobileChessInteraction, ChessPosition, ComputerMoveAnalysis, GameSession, PlayGameMode, ComputerMoveRequest, PieceType, PlayGameActions, MobileBoardState, PlayGameResult, PlayerInfo, GameResultType, GameResult, GameSettings, ChessMove, PieceColor, WrapperPiece, ChessMoveResult, MobileBoardDimensions, MobileTouchEvent, CastlingRights, GameMoveRecord, ChessMoveInput, ComputerOpponentConfig, PlayGameState, ComputerDifficulty, MobileChessConfig, MobileChessGameState, ChessGameState, MobileSquareState, ComputerMoveResult, ChessPiece, MobilePieceAnimation, ComputerThinkingState } from './chess';
export type { ActionSheetProps, BackgroundEffectProps, BackgroundEffectConfig, IBackgroundEffectsService, ChessboardProps, PieceProps, SquareProps, PlayChessboardProps, BackgroundEffectVariant, DraggedPieceProps, ActionSheetAction, BoardProps, ActionSheetContainerProps } from './core';
export type { AudioDemoHook, ExclusionExample, DemoSection, DataTableProps, DemoButtonExample, DragTestState, DragTestActions, UITestNavigationActions, UITestNavigationState, DataTableColumn, UITestRoute, UITestNavigationHook, AudioDemoConfiguration, MoveHandler, CodeSnippet, DragTestingHook, DragTestConfiguration, AudioDemoActions, AudioDemoState } from './ui';
export type { UserPreferences, UserManagementError, UserRole, UserStats, UserSession, UserManagementResponse, NotificationSettings, UserProfile, GameplaySettings, ChangePasswordData, PrivacySettings, UpdateProfileData, PaginatedUsersResponse } from './user-management';