"""
Parent Page Generator - Creates parent pages following Phase 2 Mobile Switching Architecture
"""

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dynamic_page_generator import PageConfig

# Add shared utilities to path
import sys
sys.path.append(str(Path(__file__).parent.parent.parent / "shared"))
from file_utils import write_file_with_warning


class ParentPageGenerator:
    """Generates parent pages that follow the Phase 2 Mobile Switching Architecture"""
    
    def __init__(self, pages_dir: Path, instructions_pages_dir: Path, actions_pages_dir: Path, components_dir: Path):
        self.pages_dir = pages_dir
        self.instructions_pages_dir = instructions_pages_dir
        self.actions_pages_dir = actions_pages_dir
        self.components_dir = components_dir
    
    def create_parent_page(self, config: 'PageConfig') -> None:
        """Create parent page following Phase 2 Mobile Switching Architecture"""
        parent_name = config.base_name.capitalize()
        
        content = f'''import React from "react";
import {{ useAppStore }} from "../../stores/appStore";
import {{ useIsMobile }} from "../../hooks/core/useIsMobile";
import {{ {parent_name}MainPage }} from "./{parent_name}MainPage";

// Child page wrapper imports will be added by the generator

interface {parent_name}PageProps {{
  // Add props as needed
}}

export const {parent_name}Page: React.FC<{parent_name}PageProps> = () => {{
  const currentChildPage = useAppStore((state) => state.currentChildPage);
  const isMobile = useIsMobile();
  
  // Default to main page
  let CurrentPageComponent = {parent_name}MainPage;
  
  // Child page routing with mobile switching
  // Routes will be auto-generated by the page generator
  
  // Force proper re-mounting when switching device types
  const componentKey = currentChildPage 
    ? `${{currentChildPage}}-${{isMobile ? 'mobile' : 'desktop'}}`
    : 'main';
  
  return <CurrentPageComponent key={{componentKey}} />;
}};'''
        
        # Create parent page file
        parent_page_path = self.pages_dir / config.base_name.lower() / f"{parent_name}Page.tsx"
        write_file_with_warning(
            parent_page_path,
            content,
            "ParentPageGenerator", 
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )
        
        # Also create the main page that serves as the landing page
        self._create_parent_main_page(config)
        
        # Create parent page actions and instructions  
        self._create_parent_actions(config)
        self._create_parent_instructions(config)
        
        # Create parent page wrapper with hooks
        self._create_parent_wrapper(config)
        
        # Create navigation actions hook
        self._create_navigation_actions_hook(config)
        
        print(f"  ✅ Created parent page: {parent_name}Page.tsx")
        print(f"  ✅ Created main page: {parent_name}MainPage.tsx")
        print(f"  ✅ Created parent wrapper: {parent_name}PageWrapper.tsx")
        print(f"  ✅ Created parent actions: {config.base_name.lower()}.ts")
        print(f"  ✅ Created parent instructions: {config.base_name.lower()}.ts")
        print(f"  ✅ Created navigation hook: use{parent_name}Actions.ts")

    def _create_parent_main_page(self, config: 'PageConfig') -> None:
        """Create the main landing page for the parent"""
        parent_name = config.base_name.capitalize()
        
        content = f'''import React from "react";
import {{ usePageData }} from "../../hooks/core/usePageData";
import {{ ChessboardLayout }} from "../../components/chess/ChessboardLayout";
import {{ DataTable }} from "../../components/ui/DataTable";

interface {parent_name}MainPageProps {{
  // Add props as needed
}}

export const {parent_name}MainPage: React.FC<{parent_name}MainPageProps> = () => {{
  const {{ data, loading, error }} = usePageData("{config.base_name.lower()}");

  return (
    <div className="uitest-layout-container">
      <ChessboardLayout
        topLeft={{<div className="uitest-layout-corner">{parent_name} Top Left</div>}}
        top={{<div className="uitest-layout-center"></div>}}
        topRight={{<div className="uitest-layout-corner">{parent_name} Top Right</div>}}
        left={{<div className="uitest-layout-corner">{parent_name} Left</div>}}
        center={{<DataTable data={{data}} loading={{loading}} error={{error}} />}}
        right={{<div className="uitest-layout-corner">{parent_name} Right</div>}}
        bottomLeft={{<div className="uitest-layout-corner">{parent_name} Bottom Left</div>}}
        bottom={{<div className="uitest-layout-center"></div>}}
        bottomRight={{<div className="uitest-layout-corner">{parent_name} Bottom Right</div>}}
        className="w-full h-full"
      />
    </div>
  );
}};'''
        
        main_page_path = self.pages_dir / config.base_name.lower() / f"{parent_name}MainPage.tsx"
        write_file_with_warning(
            main_page_path,
            content,
            "ParentPageGenerator",
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )

    def _create_parent_actions(self, config: 'PageConfig') -> None:
        """Create parent page action configuration"""
        content = f'''import {{ Settings, Home, Grid3x3 }} from 'lucide-react'
import type {{ ActionSheetAction }} from '../../../types/core/action-sheet.types'

export const pageActions = {{
  id: '{config.base_name.lower()}',
  actions: [
    {{
      id: '{config.base_name.lower()}-overview',
      label: '{config.base_name.capitalize()} Overview',
      icon: Home,
      variant: 'default'
    }},
    {{
      id: '{config.base_name.lower()}-grid',
      label: 'View Grid',
      icon: Grid3x3,
      variant: 'secondary'
    }},
    {{
      id: '{config.base_name.lower()}-settings',
      label: 'Settings',
      icon: Settings,
      variant: 'secondary'
    }}
  ] as ActionSheetAction[]
}}'''
        
        action_file_path = self.actions_pages_dir / f"{config.base_name.lower()}.ts"
        write_file_with_warning(
            action_file_path,
            content,
            "ParentPageGenerator",
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )

    def _create_parent_instructions(self, config: 'PageConfig') -> None:
        """Create parent page instruction configuration"""
        content = f'''export const pageInstructions = {{
  id: '{config.base_name.lower()}',
  title: '{config.base_name.capitalize()} Instructions',
  instructions: [
    'Welcome to the {config.base_name.lower()} section',
    'Use the action sheet to navigate to child pages',
    'This page supports both mobile and desktop layouts',
    'Child pages will automatically adapt to your device'
  ]
}}'''
        
        instruction_file_path = self.instructions_pages_dir / f"{config.base_name.lower()}.ts"
        write_file_with_warning(
            instruction_file_path,
            content,
            "ParentPageGenerator",
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )

    def _create_parent_wrapper(self, config: 'PageConfig') -> None:
        """Create parent page wrapper with hooks"""
        parent_name = config.base_name.capitalize()
        
        content = f'''import React from "react";
import {{ usePageInstructions }} from "../../hooks/core/usePageInstructions";
import {{ usePageActions }} from "../../hooks/core/usePageActions";
import {{ {parent_name}Page }} from "../../pages/{config.base_name.lower()}/{parent_name}Page";

export const {parent_name}PageWrapper: React.FC = () => {{
  usePageInstructions("{config.base_name.lower()}");
  usePageActions("{config.base_name.lower()}");
  
  return <{parent_name}Page />;
}};'''
        
        wrapper_path = self.components_dir / config.base_name.lower() / f"{parent_name}PageWrapper.tsx"
        write_file_with_warning(
            wrapper_path,
            content,
            "ParentPageGenerator",
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )

    def _create_navigation_actions_hook(self, config: 'PageConfig') -> None:
        """Create navigation actions hook for parent page following architecture doc patterns"""
        parent_name = config.base_name.capitalize()
        parent_id = config.base_name.lower()
        
        # Create the navigation hook based on architecture doc patterns
        content = f'''import {{ useCallback }} from 'react'
import {{ useAppStore }} from '../../stores/appStore'

export function use{parent_name}Actions() {{
  const setCurrentChildPage = useAppStore((state) => state.setCurrentChildPage)
  const setSelectedTab = useAppStore((state) => state.setSelectedTab)

  // Navigation to other parent tabs
  const goToUitests = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setSelectedTab('uitests')
      setCurrentChildPage(null)
    }}, 100)
  }}, [setSelectedTab, setCurrentChildPage])

  const goToCasino = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setSelectedTab('casino')
      setCurrentChildPage(null)
    }}, 100)
  }}, [setSelectedTab, setCurrentChildPage])

  const goToNewparent = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('newparent')
    }}, 100)
  }}, [setCurrentChildPage])

  const goToTestparent = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('testparent')
    }}, 100)
  }}, [setCurrentChildPage])

  // Navigation to child pages within this parent
  const goToDragTest = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('dragtest')
    }}, 100)
  }}, [setCurrentChildPage])

  const goToAudioTest = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('uiaudiotest')
    }}, 100)
  }}, [setCurrentChildPage])

  const goToLayoutTest = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('layouttest')
    }}, 100)
  }}, [setCurrentChildPage])

  const goToChessLayoutTest = useCallback(() => {{
    // Small delay to prevent hover sound from triggering after menu transition
    setTimeout(() => {{
      setCurrentChildPage('chesslayouttest')
    }}, 100)
  }}, [setCurrentChildPage])

  return {{
    // Navigation to other parent tabs
    goToUitests,
    goToCasino,
    goToNewparent,
    goToTestparent,
    // Navigation to child pages
    goToDragTest,
    goToAudioTest,
    goToLayoutTest,
    goToChessLayoutTest
  }}
}}'''
        
        # Create hook file in hooks directory
        hooks_dir = Path(self.components_dir).parent / "hooks" / config.base_name.lower()
        hooks_dir.mkdir(parents=True, exist_ok=True)
        
        hook_path = hooks_dir / f"use{parent_name}Actions.ts"
        write_file_with_warning(
            hook_path,
            content,
            "ParentPageGenerator",
            "/tools/frontend-tools/mobile-pages/generators/parent_page_generator.py"
        )