/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import { Navigation } from 'lucide-react'
import type { ActionSheetAction } from '../../../types/core/action-sheet.types'

export const pageActions = {
  id: 'chess',
  actions: [
    // Child navigation actions
        {
      id: 'go-to-playchess',
      label: 'Go to PlayChess',
      icon: Navigation,
      variant: 'secondary'
    },
    {
      id: 'go-to-playpuzzles',
      label: 'Go to PlayPuzzles',
      icon: Navigation,
      variant: 'secondary'
    },
  ] as ActionSheetAction[]
}