<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './chess.types';
export * from './computer-opponent.types';
export * from './mobile-chess.types';
export * from './play-game.types';
export * from './wrapper-piece.types';
=======
// Auto-generated barrel export for chess
// Generated by AdvancedBarrelGenerator

// Named exports only
export type * from './chess.types';
export type * from './computer-opponent.types';
export * from './mobile-chess.types';
export type * from './play-game.types';
export type * from './wrapper-piece.types';
>>>>>>> Stashed changes
