#!/usr/bin/env python3
"""
Integration tests for full page generation workflow.
Tests the complete end-to-end generation process from CLI to file output.
"""

import sys
import os
import tempfile
import shutil
from pathlib import Path
from unittest.mock import Mock, patch

# Add modules to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../../shared'))

def test_full_parent_generation():
    """Test complete parent page generation workflow."""
    print("\n=== Testing Full Parent Generation ===")
    
    try:
        from main import TemplateBasedGeneratorCLI
        
        # Setup test environment
        temp_dir = Path(tempfile.mkdtemp())
        templates_dir = Path(__file__).parent.parent.parent / "templates"
        
        # Create basic project structure
        src_dir = temp_dir / "src"
        (src_dir / "pages").mkdir(parents=True)
        (src_dir / "components").mkdir(parents=True)
        (src_dir / "hooks" / "core").mkdir(parents=True)
        (src_dir / "constants" / "actions").mkdir(parents=True)
        (src_dir / "services" / "instructions").mkdir(parents=True)
        (temp_dir / "package.json").write_text('{"name": "test-project"}')
        
        # Initialize CLI
        cli = TemplateBasedGeneratorCLI(str(temp_dir))
        
        # Test 1: Create parent page
        cli.create_parent_page("Dashboard")
        
        # Verify parent files were created
        dashboard_dir = src_dir / "pages" / "dashboard"
        assert dashboard_dir.exists(), "Dashboard directory not created"
        
        expected_files = [
            "DashboardPage.tsx",
            "DashboardMainPage.tsx"
        ]
        
        for file_name in expected_files:
            file_path = dashboard_dir / file_name
            assert file_path.exists(), f"Expected file not created: {file_name}"
            
            # Verify file content
            content = file_path.read_text()
            assert "Dashboard" in content, f"Content missing Dashboard reference in {file_name}"
            assert "// Generated by" in content, f"Missing generator header in {file_name}"
        
        # Verify hooks were created
        hooks_dir = src_dir / "hooks" / "pages" / "dashboard"
        assert hooks_dir.exists(), "Dashboard hooks directory not created"
        
        # Verify actions were created
        actions_file = src_dir / "constants" / "actions" / "pages" / "dashboard" / "dashboard-actions.ts"
        assert actions_file.exists(), "Dashboard actions file not created"
        
        # Verify instructions were created
        instructions_file = src_dir / "services" / "instructions" / "pages" / "dashboard" / "dashboard-instructions.ts"
        assert instructions_file.exists(), "Dashboard instructions file not created"
        
        print("✅ Parent page generation workflow")
        
        # Cleanup
        shutil.rmtree(temp_dir)
        
        return True
        
    except Exception as e:
        print(f"❌ Full parent generation test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_full_child_generation():
    """Test complete child page generation workflow."""
    print("\n=== Testing Full Child Generation ===")
    
    try:
        from main import TemplateBasedGeneratorCLI
        
        # Setup test environment  
        temp_dir = Path(tempfile.mkdtemp())
        templates_dir = Path(__file__).parent.parent.parent / "templates"
        
        # Create basic project structure
        src_dir = temp_dir / "src"
        (src_dir / "pages").mkdir(parents=True)
        (src_dir / "components").mkdir(parents=True)
        (src_dir / "hooks" / "core").mkdir(parents=True)
        (src_dir / "constants" / "actions").mkdir(parents=True)
        (src_dir / "services" / "instructions").mkdir(parents=True)
        (temp_dir / "package.json").write_text('{"name": "test-project"}')
        
        # Create necessary hooks for capabilities
        core_hooks = src_dir / "hooks" / "core"
        (core_hooks / "usePageInstructions.ts").write_text("export const usePageInstructions = () => {};")
        (core_hooks / "usePageActions.ts").write_text("export const usePageActions = () => {};")
        (core_hooks / "useIsMobile.ts").write_text("export const useIsMobile = () => {};")
        
        # Initialize CLI
        cli = TemplateBasedGeneratorCLI(str(temp_dir))
        
        # Test 1: Create parent page first
        cli.create_parent_page("Settings")
        
        # Test 2: Create child page
        cli.create_child_page("UserProfile", "Settings", mobile=True)
        
        # Verify child files were created
        settings_dir = src_dir / "pages" / "settings"
        
        expected_child_files = [
            "UserProfilePage.tsx",
            "MobileUserProfilePage.tsx"
        ]
        
        for file_name in expected_child_files:
            file_path = settings_dir / file_name
            assert file_path.exists(), f"Expected child file not created: {file_name}"
            
            content = file_path.read_text()
            assert "UserProfile" in content, f"Content missing UserProfile reference in {file_name}"
        
        # Verify wrapper was created
        wrapper_dir = src_dir / "components" / "settings"
        wrapper_file = wrapper_dir / "UserProfileWrapper.tsx"
        assert wrapper_file.exists(), "UserProfile wrapper not created"
        
        wrapper_content = wrapper_file.read_text()
        assert "useIsMobile" in wrapper_content, "Mobile hook not included in wrapper"
        
        # Verify parent routing was updated
        parent_file = settings_dir / "SettingsPage.tsx"
        parent_content = parent_file.read_text()
        assert "UserProfileWrapper" in parent_content, "Parent routing not updated with child import"
        assert "userprofile" in parent_content, "Parent routing not updated with child route"
        
        # Verify child hooks were created
        child_hooks_dir = src_dir / "hooks" / "pages" / "settings"
        child_actions_hook = child_hooks_dir / "useUserProfileActions.ts"
        assert child_actions_hook.exists(), "Child actions hook not created"
        
        print("✅ Child page generation workflow")
        
        # Cleanup
        shutil.rmtree(temp_dir)
        
        return True
        
    except Exception as e:
        print(f"❌ Full child generation test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_full_project_analysis():
    """Test complete project analysis workflow."""
    print("\n=== Testing Full Project Analysis ===")
    
    try:
        from main import TemplateBasedGeneratorCLI
        
        # Setup test environment with existing project structure
        temp_dir = Path(tempfile.mkdtemp())
        src_dir = temp_dir / "src"
        (src_dir / "pages").mkdir(parents=True)
        (src_dir / "components").mkdir(parents=True)
        (src_dir / "hooks" / "core").mkdir(parents=True)
        (temp_dir / "package.json").write_text('{"name": "test-project"}')
        
        # Create existing pages structure
        dashboard_dir = src_dir / "pages" / "dashboard"
        dashboard_dir.mkdir(parents=True)
        (dashboard_dir / "DashboardPage.tsx").write_text("export default function DashboardPage() {}")
        (dashboard_dir / "StatsPage.tsx").write_text("export default function StatsPage() {}")
        
        settings_dir = src_dir / "pages" / "settings"  
        settings_dir.mkdir(parents=True)
        (settings_dir / "SettingsPage.tsx").write_text("export default function SettingsPage() {}")
        (settings_dir / "UserProfilePage.tsx").write_text("export default function UserProfilePage() {}")
        
        # Create hooks for capability detection
        core_hooks = src_dir / "hooks" / "core"
        (core_hooks / "usePageInstructions.ts").write_text("export const usePageInstructions = () => {};")
        (core_hooks / "usePageActions.ts").write_text("export const usePageActions = () => {};")
        (core_hooks / "useIsMobile.ts").write_text("export const useIsMobile = () => {};")
        
        # Initialize CLI
        cli = TemplateBasedGeneratorCLI(str(temp_dir))
        
        # Capture output from analysis
        import io
        from contextlib import redirect_stdout
        
        captured_output = io.StringIO()
        with redirect_stdout(captured_output):
            cli.analyze_project()
        
        output = captured_output.getvalue()
        
        # Verify analysis detected structure correctly
        assert "Dashboard" in output, "Dashboard parent not detected"
        assert "Settings" in output, "Settings parent not detected"  
        assert "has_page_hooks: True" in output, "Page hooks capability not detected"
        assert "has_mobile_hook: True" in output, "Mobile hook capability not detected"
        
        print("✅ Project analysis workflow")
        
        # Cleanup
        shutil.rmtree(temp_dir)
        
        return True
        
    except Exception as e:
        print(f"❌ Full project analysis test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_error_handling_workflow():
    """Test error handling in generation workflow.""" 
    print("\n=== Testing Error Handling Workflow ===")
    
    try:
        from main import TemplateBasedGeneratorCLI
        
        # Test 1: Invalid frontend root
        try:
            TemplateBasedGeneratorCLI("/nonexistent/path")
            assert False, "Should have raised error for invalid path"
        except ValueError as e:
            assert "not found" in str(e), "Should mention path not found"
        
        # Test 2: Creating child without parent
        temp_dir = Path(tempfile.mkdtemp())
        src_dir = temp_dir / "src"
        (src_dir / "pages").mkdir(parents=True)
        (src_dir / "components").mkdir(parents=True)
        (src_dir / "hooks" / "core").mkdir(parents=True)
        (temp_dir / "package.json").write_text('{"name": "test-project"}')
        
        cli = TemplateBasedGeneratorCLI(str(temp_dir))
        
        # This should fail gracefully
        try:
            cli.create_child_page("TestChild", "NonExistentParent")
            assert False, "Should have failed for missing parent"
        except SystemExit:
            pass  # Expected behavior
        
        print("✅ Error handling workflow")
        
        # Cleanup
        shutil.rmtree(temp_dir)
        
        return True
        
    except Exception as e:
        print(f"❌ Error handling workflow test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    """Run all integration tests."""
    print("🧪 Running Integration Tests - Full Generation Workflow")
    print("=" * 70)
    
    all_passed = True
    
    # Run all test functions
    test_functions = [
        test_full_parent_generation,
        test_full_child_generation, 
        test_full_project_analysis,
        test_error_handling_workflow
    ]
    
    for test_func in test_functions:
        try:
            passed = test_func()
            all_passed &= passed
        except Exception as e:
            print(f"❌ Test function {test_func.__name__} failed: {e}")
            all_passed = False
    
    # Final results
    print("\n" + "=" * 70)
    print("🧪 INTEGRATION TEST RESULTS")
    print("=" * 70)
    
    if all_passed:
        print("🎉 ALL INTEGRATION TESTS PASSED!")
        print("✅ Full generation workflow is working correctly")
    else:
        print("❌ SOME INTEGRATION TESTS FAILED!")
        print("⚠️  Full generation workflow needs attention")
    
    print("=" * 70)
    return 0 if all_passed else 1

if __name__ == "__main__":
    sys.exit(main())