/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for Achievement

export interface Achievement {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  points: number;
  difficulty: string;
  requirements: string;
  created_at: string;
  updated_at: string;
}

export interface AchievementCreate {
  // Properties needed for creating new Achievement
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  points: number;
  difficulty: string;
  requirements: string;
  created_at: string;
  updated_at: string;
}

export interface AchievementUpdate {
  // Properties that can be updated
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  points: number;
  difficulty: string;
  requirements: string;
  created_at: string;
  updated_at: string;
}

export interface AchievementFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
