/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for UserProfile

export interface UserProfile {
  id: string;
  user_id: string;
  display_name: string;
  avatar_url: string;
  bio: string;
  country: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface UserProfileCreate {
  // Properties needed for creating new UserProfile
  id: string;
  user_id: string;
  display_name: string;
  avatar_url: string;
  bio: string;
  country: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface UserProfileUpdate {
  // Properties that can be updated
  id: string;
  user_id: string;
  display_name: string;
  avatar_url: string;
  bio: string;
  country: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface UserProfileFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
