/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated types for UserAchievement

export interface UserAchievement {
  id: string;
  user_id: string;
  achievement_id: string;
  earned_at: string;
  progress: number;
  created_at: string;
  updated_at: string;
}

export interface UserAchievementCreate {
  // Properties needed for creating new UserAchievement
  id: string;
  user_id: string;
  achievement_id: string;
  earned_at: string;
  progress: number;
  created_at: string;
  updated_at: string;
}

export interface UserAchievementUpdate {
  // Properties that can be updated
  id: string;
  user_id: string;
  achievement_id: string;
  earned_at: string;
  progress: number;
  created_at: string;
  updated_at: string;
}

export interface UserAchievementFilter {
  // Properties for filtering/searching
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}
