/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export type { ElementDetectionResult, GlobalUIAudioConfig, UISoundType, UIInteractionType, GlobalUIAudioService, UIExclusionConfig, UIElementSelector, GlobalUIAudioConfigUpdate, GlobalClickHandler, UIInteractionConfig } from './audio';
export type { AuthApiClient, AuthError, RegisterResponse, UseAuthReturn, VerifyTokenRequest, AuthErrorType, UseRegisterReturn, ChangePasswordRequest, LoginResponse, AuthGuardProps, FormValidationError, UserProgress, UpdateProfileRequest, MeResponse, ProtectedRouteProps, RegisterRequest, AuthState, TokenVerificationResponse, AuthContextValue, LoginCredentials, AuthConfig, UseLoginReturn, LoginRequest, AuthStorage, User, AuthActions, TokenInfo, ResetPasswordRequest, AuthResponse, UseForgotPasswordReturn, RegisterData, ForgotPasswordRequest, AuthFormState } from './auth';
export type { ActionSheetAction, BackgroundEffectVariant, ActionSheetContainerProps, BackgroundEffectConfig, ActionSheetProps, IBackgroundEffectsService, BackgroundEffectProps } from './core';
export type { GameplaySettings, ChangePasswordData, UserProfile, PrivacySettings, UserStats, UserManagementError, UserPreferences, UserManagementResponse, UpdateProfileData, UserRole, PaginatedUsersResponse, UserSession, NotificationSettings } from './user-management';