/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

// globalUIAudioService.ts - Global UI audio service using existing audio service

import type { 
  GlobalUIAudioService as IGlobalUIAudioService, 
  GlobalUIAudioConfig, 
  GlobalUIAudioConfigUpdate
} from '../../types/audio/global-audio.types';
import type { UIElementSelector } from '../../types/audio/ui-audio.types';
import { audioService } from './audioService';
import { getDeviceInfo } from '../../utils/audio/deviceDetection';
import { EventDeduplicator } from '../../utils/audio/eventDeduplication';
import { getElementInfo } from '../../utils/audio/componentDetection';

const DEFAULT_CONFIG: GlobalUIAudioConfig = {
  enabled: true,
  autoDetection: true,
  customSelectors: [],
  excludeSelectors: [],
  exclusions: []
};

/**
 * Global UI Audio Service Implementation
 * Provides sound feedback for UI interactions using the existing audio service
 */
export class GlobalUIAudioService implements IGlobalUIAudioService {
  private config: GlobalUIAudioConfig;
  private initialized = false;
  private deviceInfo = getDeviceInfo();
  private eventDeduplicator = new EventDeduplicator();

  constructor(initialConfig: Partial<GlobalUIAudioConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...initialConfig };
  }

  public initialize(): void {
    if (this.initialized) {
      return;
    }
    
    // Add event listeners to play sounds
    window.addEventListener('click', this.handleGlobalClick.bind(this), true);
    window.addEventListener('mouseover', this.handleGlobalHover.bind(this), true);
    
    this.initialized = true;
  }

  public destroy(): void {
    if (!this.initialized) {
      return;
    }
    
    // Clean up event deduplicator
    this.eventDeduplicator.destroy();
    
    window.removeEventListener('click', this.handleGlobalClick.bind(this), true);
    window.removeEventListener('mouseover', this.handleGlobalHover.bind(this), true);
    
    this.initialized = false;
  }

  private playMoveSound(): void {
    if (!this.config.enabled) return;
    audioService.playMove(false);
  }

  private playCaptureSound(): void {
    if (!this.config.enabled) return;
    audioService.playMove(true);
  }

  public configure(configUpdate: GlobalUIAudioConfigUpdate): void {
    this.config = { ...this.config, ...configUpdate };
  }

  public addCustomSelector(_selector: UIElementSelector): void {
    // Stub - do nothing
  }

  public removeCustomSelector(_selectorString: string): void {
    // Stub - do nothing  
  }

  private handleGlobalClick(event: Event): void {
    const target = event.target as HTMLElement;
    
    // Handle deduplication and sequence detection
    this.eventDeduplicator.handleClick(target);
    
    // Log component information for clicks
    const elementInfo = getElementInfo(target);
    const identifier = elementInfo.textContent || elementInfo.className || elementInfo.id || elementInfo.tagName;
    console.log('🖱️ CLICK:', identifier);
    
    // Play capture sound on click
    this.playCaptureSound();
  }

  private handleGlobalHover(event: Event): void {
    const target = event.target as HTMLElement;
    
    // Use the event deduplicator to handle hover
    this.eventDeduplicator.trackHover(
      target,
      () => {
        // Play move sound on hover
        this.playMoveSound();
      },
      this.deviceInfo.isMobile
    );
  }


  public getConfig(): GlobalUIAudioConfig {
    return { ...this.config };
  }

  public isInitialized(): boolean {
    return this.initialized;
  }
}