/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface GameResponse {
  id: string;
  user_id: string;
  ai_level: number;
  user_color: string;
  current_fen: string;
  pgn: string;
  status: string;
  result: string;
  time_control: string;
  started_at: string;
  completed_at: string;
  created_at: string;
  updated_at: string;
}

export interface CreateGameRequest {
  user_id: string;
  ai_level: number;
  user_color: string;
  current_fen: string;
  pgn: string;
  status: string;
  result: string;
  time_control: string;
  started_at: string;
  completed_at: string;
}

export interface UpdateGameRequest {
  user_id?: string;
  ai_level?: number;
  user_color?: string;
  current_fen?: string;
  pgn?: string;
  status?: string;
  result?: string;
  time_control?: string;
  started_at?: string;
  completed_at?: string;
}