/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface OpeningResponse {
  id: string;
  name: string;
  eco_code: string;
  moves: string;
  description: string;
  popularity_score: number;
  difficulty_level: string;
  created_at: string;
  updated_at: string;
}

export interface CreateOpeningRequest {
  name: string;
  eco_code: string;
  moves: string;
  description: string;
  popularity_score: number;
  difficulty_level: string;
}

export interface UpdateOpeningRequest {
  name?: string;
  eco_code?: string;
  moves?: string;
  description?: string;
  popularity_score?: number;
  difficulty_level?: string;
}