/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface PuzzleResponse {
  id: string;
  fen: string;
  solution_moves: string;
  themes: theme[];
  rating: number;
  description: string;
  created_at: string;
  updated_at: string;
}

export interface CreatePuzzleRequest {
  fen: string;
  solution_moves: string;
  themes: theme[];
  rating: number;
  description: string;
}

export interface UpdatePuzzleRequest {
  fen?: string;
  solution_moves?: string;
  themes?: theme[];
  rating?: number;
  description?: string;
}

export interface theme {
  theme: string;
}