/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface PuzzleSourceResponse {
  id: string;
  source_id: string;
  name: string;
  description: string;
  total_puzzles: number;
  average_rating: number;
  is_active: boolean;
  attribution: string;
  license: string;
  url: string;
  created_at: string;
  updated_at: string;
}

export interface CreatePuzzleSourceRequest {
  source_id: string;
  name: string;
  description: string;
  total_puzzles: number;
  average_rating: number;
  is_active: boolean;
  attribution: string;
  license: string;
  url: string;
}

export interface UpdatePuzzleSourceRequest {
  source_id?: string;
  name?: string;
  description?: string;
  total_puzzles?: number;
  average_rating?: number;
  is_active?: boolean;
  attribution?: string;
  license?: string;
  url?: string;
}