/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface UserProfileResponse {
  id: string;
  user_id: string;
  display_name: string;
  avatar_url: string;
  bio: string;
  country: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface CreateUserProfileRequest {
  user_id: string;
  display_name: string;
  avatar_url: string;
  bio: string;
  country: string;
  timezone: string;
}

export interface UpdateUserProfileRequest {
  user_id?: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  country?: string;
  timezone?: string;
}