/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the backend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/backend-tools/backend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export interface UserAchievementResponse {
  id: string;
  user_id: string;
  achievement_id: string;
  earned_at: string;
  progress: number;
  created_at: string;
  updated_at: string;
}

export interface CreateUserAchievementRequest {
  user_id: string;
  achievement_id: string;
  earned_at: string;
  progress: number;
}

export interface UpdateUserAchievementRequest {
  user_id?: string;
  achievement_id?: string;
  earned_at?: string;
  progress?: number;
}