<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './DashboardPage';
=======
// Auto-generated barrel export for dashboard
// Generated by AdvancedBarrelGenerator

// Named exports only
export * from './DashboardPage';
>>>>>>> Stashed changes
