/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

/**
 * Dynamic PAGE_ACTIONS Registry - Generated from pages.config.json
 * 
 * This registry automatically imports all generated page actions and provides
 * dynamic action discovery for the ActionSheetContainer.
 */
import type { ActionSheetAction } from '../../types/core/action-sheet.types'
import { mergeWithCommonActions } from './common-actions.constants'

// Dynamic imports for all generated page actions
import { pageActions as playchessActions } from "./pages/playchess";
import { pageActions as playpuzzlesActions } from "./pages/playpuzzles";
import { pageActions as chessActions } from "./pages/chess";
import { pageActions as workerActions } from "./pages/worker";

/**
 * Central registry of all page actions.
 * Automatically updated when new pages are generated.
 */
export const PAGE_ACTIONS: Record<string, ActionSheetAction[]> = {
  playchess: mergeWithCommonActions([
    ...playchessActions.actions
  ], ['go-to-playpuzzles']),
  playpuzzles: mergeWithCommonActions([
    ...playpuzzlesActions.actions
  ], ['go-to-playchess']),
  chess: mergeWithCommonActions([...chessActions.actions], []),
  worker: mergeWithCommonActions([...workerActions.actions], []),
}

/**
 * Helper function to get actions for a specific page.
 * Returns empty array if page not found.
 */
export function getPageActions(pageId: string): ActionSheetAction[] {
  return PAGE_ACTIONS[pageId] || [];
}

/**
 * Helper function to check if page has actions.
 */
export function hasPageActions(pageId: string): boolean {
  const actions = PAGE_ACTIONS[pageId];
  return actions && actions.length > 0;
}

/**
 * Get all page IDs that have actions defined.
 */
export function getPageIdsWithActions(): string[] {
  return Object.keys(PAGE_ACTIONS);
}