<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './CoinsModal';
=======
// Auto-generated barrel export for casino
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './CoinsModal';

// Default export for single component barrel
export { default as default } from './CoinsModal';
>>>>>>> Stashed changes
