/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

// Generated service for Game
import type { Game } from '../../types/chess/games';

export interface ApiResponse<T> {
  data: T;
  message?: string;
  success: boolean;
}

class GameService {
  private baseUrl: string;

  constructor(baseUrl: string = '/api') {
    this.baseUrl = baseUrl;
  }

  private async handleResponse<T>(response: Response): Promise<T> {
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  private getHeaders(): Record<string, string> {
    const token = localStorage.getItem('authToken');
    return {
      'Content-Type': 'application/json',
      ...(token && { Authorization: `Bearer ${token}` })
    };
  }

  async createGame(data: Partial<Game>): Promise<Game> {
    const response = await fetch(`${this.baseUrl}/games`, {
      method: 'POST',
      headers: this.getHeaders(),
      body: JSON.stringify(data)
    });
    return this.handleResponse<Game>(response);
  }

  async getGameById(id: string): Promise<Game> {
    const response = await fetch(`${this.baseUrl}/games/${id}`, {
      method: 'GET',
      headers: this.getHeaders()
    });
    return this.handleResponse<Game>(response);
  }

  async listGames(): Promise<Game[]> {
    const response = await fetch(`${this.baseUrl}/games`, {
      method: 'GET',
      headers: this.getHeaders()
    });
    return this.handleResponse<Game[]>(response);
  }

  async updateGame(id: string, data: Partial<Game>): Promise<Game> {
    const response = await fetch(`${this.baseUrl}/games/${id}`, {
      method: 'PUT',
      headers: this.getHeaders(),
      body: JSON.stringify(data)
    });
    return this.handleResponse<Game>(response);
  }

  async deleteGame(id: string): Promise<void> {
    const response = await fetch(`${this.baseUrl}/games/${id}`, {
      method: 'DELETE',
      headers: this.getHeaders()
    });
    await this.handleResponse<void>(response);
  }
}

export const gamesService = new GameService();
export default gamesService;