/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { PlayMainPage } from "../../components/play/PlayMainPage";
import { PlayChessPageWrapper } from "../../components/play/PlayChessPageWrapper";
import { PlayPuzzlesPageWrapper } from "../../components/play/PlayPuzzlesPageWrapper";

export const PlayPage: React.FC = () => {
  const currentChildPage = useAppStore((state) => state.currentChildPage);

  // Determine which component to render
  let CurrentPageComponent = PlayMainPage;

  if (currentChildPage === "playchess") {
    CurrentPageComponent = PlayChessPageWrapper;
  } else if (currentChildPage === "playpuzzles") {
    CurrentPageComponent = PlayPuzzlesPageWrapper;
  }

  return (
    <div className="relative h-full">
      {/* Current page content */}
      <CurrentPageComponent />
    </div>
  );
};