<<<<<<< Updated upstream
// Auto-generated index file - DO NOT EDIT MANUALLY

export * from './BackgroundEffectsRenderer';

export * from './effects';
=======
// Auto-generated barrel export for background-effects
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './BackgroundEffectsRenderer';
export { default as BackgroundEffectsRenderer } from './BackgroundEffectsRenderer';

// Subdirectory exports
export * from './effects';
>>>>>>> Stashed changes
