/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the IndexGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/index-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

export type { UIElementSelector, GlobalClickHandler, UIInteractionType, UIExclusionConfig, UIInteractionConfig, GlobalUIAudioConfigUpdate, ElementDetectionResult, UISoundType, GlobalUIAudioService, GlobalUIAudioConfig } from './audio';
export type { RegisterRequest, AuthGuardProps, UseRegisterReturn, AuthState, UserProgress, ChangePasswordRequest, AuthFormState, UseLoginReturn, AuthErrorType, AuthActions, AuthStorage, TokenVerificationResponse, FormValidationError, ForgotPasswordRequest, AuthResponse, LoginCredentials, LoginResponse, RegisterData, TokenInfo, User, UseForgotPasswordReturn, RegisterResponse, MeResponse, AuthError, AuthApiClient, ProtectedRouteProps, UpdateProfileRequest, VerifyTokenRequest, AuthContextValue, ResetPasswordRequest, UseAuthReturn, LoginRequest, AuthConfig } from './auth';
export type { BackgroundEffectProps, IBackgroundEffectsService, BackgroundEffectVariant, ActionSheetContainerProps, ActionSheetAction, BackgroundEffectConfig, ActionSheetProps } from './core';
export type { UserPreferences, UpdateProfileData, UserRole, ChangePasswordData, UserSession, UserManagementError, GameplaySettings, UserStats, UserProfile, NotificationSettings, UserManagementResponse, PrivacySettings, PaginatedUsersResponse } from './user-management';