/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

/**
 * Dynamic PAGE_ACTIONS Registry - Generated from pages.config.json
 * 
 * This registry automatically imports all generated page actions and provides
 * dynamic action discovery for the ActionSheetContainer.
 */
import type { ActionSheetAction } from '../../types/core/action-sheet.types'
import { mergeWithCommonActions } from './common-actions.constants'

// Dynamic imports for all generated page actions
import { pageActions as testingActions } from "./pages/testing";
import { pageActions as dataanalyticsActions } from "./pages/dataanalytics";
import { pageActions as gamehubActions } from "./pages/gamehub";
import { pageActions as usermanagementActions } from "./pages/usermanagement";
import { pageActions as testbackupActions } from "./pages/testbackup";
import { pageActions as pageoneActions } from "./pages/pageone";
import { pageActions as pagetwoActions } from "./pages/pagetwo";
import { pageActions as testsectionActions } from "./pages/testsection";

/**
 * Central registry of all page actions.
 * Automatically updated when new pages are generated.
 */
export const PAGE_ACTIONS: Record<string, ActionSheetAction[]> = {
  testing: mergeWithCommonActions([...testingActions.actions], []),
  dataanalytics: mergeWithCommonActions([...dataanalyticsActions.actions], []),
  gamehub: mergeWithCommonActions([...gamehubActions.actions], []),
  usermanagement: mergeWithCommonActions([...usermanagementActions.actions], []),
  testbackup: mergeWithCommonActions([...testbackupActions.actions], []),
  pageone: mergeWithCommonActions([
    ...pageoneActions.actions
  ], ['go-to-pagetwo']),
  pagetwo: mergeWithCommonActions([
    ...pagetwoActions.actions
  ], ['go-to-pageone']),
  testsection: mergeWithCommonActions([...testsectionActions.actions], []),
}

/**
 * Helper function to get actions for a specific page.
 * Returns empty array if page not found.
 */
export function getPageActions(pageId: string): ActionSheetAction[] {
  return PAGE_ACTIONS[pageId] || [];
}

/**
 * Helper function to check if page has actions.
 */
export function hasPageActions(pageId: string): boolean {
  const actions = PAGE_ACTIONS[pageId];
  return actions && actions.length > 0;
}

/**
 * Get all page IDs that have actions defined.
 */
export function getPageIdsWithActions(): string[] {
  return Object.keys(PAGE_ACTIONS);
}