/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import React from "react";
import { useAppStore } from "../../stores/appStore";
import { usePageInstructions } from "../../hooks/core/usePageInstructions";
import { usePageActions } from "../../hooks/core/usePageActions";
// Mobile hook import will be added when mobile support is enabled
import { ActionSheetContainer } from "../../components/action-sheet/ActionSheetContainer";
import { useTestSectionActions } from "../../hooks/testsection/useTestSectionActions";
import { TestSectionMainPage } from "./TestSectionMainPage";

import { PageOnePageWrapper } from "../../components/testsection/PageOnePageWrapper";
import { PageTwoPageWrapper } from "../../components/testsection/PageTwoPageWrapper";
import { TestSectionMainPageWrapper } from "../../components/testsection/TestSectionMainPageWrapper";

interface TestSectionPageProps {
  // Add props as needed
}

export const TestSectionPage: React.FC<TestSectionPageProps> = () => {
  const currentChildPage = useAppStore((state: any) => state.currentChildPage);
  // Mobile detection will be added when mobile support is enabled
  
  // Apply page hooks directly (no wrapper needed)
  usePageInstructions("testsection");
  usePageActions("testsection");
  
  // Use parent actions hook for navigation methods
  useTestSectionActions();
  
  // Default to main page with mobile switching
  let CurrentPageComponent = TestSectionMainPage;
  
  // Child page routing - wrappers handle mobile switching internally
    if (currentChildPage === "pageone") {
    CurrentPageComponent = PageOnePageWrapper;
  } else  if (currentChildPage === "pagetwo") {
    CurrentPageComponent = PageTwoPageWrapper;
  } else  if (currentChildPage === "testsectionmain") {
    CurrentPageComponent = TestSectionMainPageWrapper;
  }
  
  // Simple key for child page re-mounting
  const componentKey = currentChildPage || 'main';
  
  return (
    <>
      <CurrentPageComponent key={componentKey} />
      <ActionSheetContainer 
        currentPage="testsection"
        onClose={() => {}}
        isOpen={false}
        onOpenSettings={() => {}}
      />
    </>
  );
};