/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ChildPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/child_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import { EyeOff } from 'lucide-react'
import type { ActionSheetAction } from '../../../types/core/action-sheet.types'

export const pageActions = {
  id: 'preferences',
  actions: [
    {
      id: 'toggle-preferences',
      label: 'Toggle Preferences',
      icon: EyeOff,
      variant: 'default'
    }
  ] as ActionSheetAction[]
}