/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the ParentPageGenerator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-v2/modules/parent_generator.py
 * 
 * Then re-run the generator to update this file.
 */

import { Settings, Home, Grid3x3, Navigation } from 'lucide-react'
import type { ActionSheetAction } from '../../../types/core/action-sheet.types'

export const pageActions = {
  id: 'settings',
  actions: [
    {
      id: 'settings-overview',
      label: 'Settings Overview',
      icon: Home,
      variant: 'default'
    },
    // Child navigation actions
    // Child navigation actions will be added here when children are created
    {
      id: 'settings-grid',
      label: 'View Grid',
      icon: Grid3x3,
      variant: 'secondary'
    },
    {
      id: 'settings-settings',
      label: 'Settings',
      icon: Settings,
      variant: 'secondary'
    }
  ] as ActionSheetAction[]
}