/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the DependencyManager.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * /tools/frontend-tools/mobile-pages-mini/modules/dependency_manager.py
 * 
 * Then re-run the generator to update this file.
 */

/**
 * Background effects configuration constants and data
 * Extracted from SettingsPanel for Single Responsibility Principle
 */

import { Sparkles, X } from "lucide-react";

/**
 * Background effects toggle button configuration
 */
export const BACKGROUND_EFFECTS_TOGGLE_BUTTONS = {
  enabled: {
    icon: Sparkles,
    label: "Enabled"
  },
  disabled: {
    icon: X,
    label: "Disabled"
  }
} as const;

/**
 * Default background effect variant when enabling effects
 */
export const DEFAULT_BACKGROUND_VARIANT = 'gaming' as const;